#!/usr/bin/env bash
# gh-account-guard.sh — PreToolUse hook guarding GitHub actions in THIS repo,
# on two axes:
#   WHO   — gh may only act as the pinned account (resolved at runtime; see
#           the WHO block — never baked into this committed file).
#   WHERE — gh may only touch the one allowlisted repo (baked below).
#
# Generated by app-factory's factory-init and SELF-CONTAINED: it ships inside
# this repo and depends on nothing outside it. GH_GUARD_USER overrides the
# account for tests. Exit 0 = proceed to normal permission evaluation; 2 = block.
set -uo pipefail

FAC_ACCOUNT_DEFAULT=''
ALLOWED_REPOS_RE='abbasihsn/factory-console'
ALLOWED_REPOS_HUMAN='abbasihsn/factory-console'

raw="$(cat)"
# Fast pre-filter: the guard only cares about gh-touching invocations plus the
# destructive-action deny below, so a payload carrying neither a "gh" nor a
# "push" substring can't match either. Skip the jq spawn entirely on those (the
# >95% of Bash calls that touch neither) to keep the PreToolUse hot path cheap.
# Downstream matching stays authoritative.
#
# "push" is in the filter because the destructive deny covers force/delete
# pushes, which the gh-detector deliberately does NOT match (see its comment).
case "$raw" in
  *gh*|*push*) ;;
  *) exit 0 ;;
esac
if command -v jq >/dev/null 2>&1; then
  have_jq=1
  cmd="$(printf '%s' "$raw" | jq -r '.tool_input.command // empty' 2>/dev/null)"
else
  # jq missing: fail CLOSED for gh-shaped input rather than silently unguarded.
  have_jq=0
  cmd="$raw"
fi
[ -n "$cmd" ] || exit 0

block() { printf 'GitHub action blocked: %s\n' "$1" >&2; exit 2; }

# --- DESTRUCTIVE ACTIONS: deny by COMMAND CONTENT, not by command prefix ------
#
# This runs BEFORE the gh-detector below, and matches ANYWHERE in the command,
# because the permission layer cannot do this job. `permissions.deny` rules are
# PREFIX matches (see lib/permissions.sh), so `Bash(gh pr merge:*)` only ever
# matches a command that BEGINS with `gh pr merge` — any granted program that
# can exec another program voids the whole deny list:
#
#   awk 'BEGIN{system("gh pr merge 5 --squash")}'   # Bash(awk:*) is granted
#   timeout 60 bash -c 'gh pr merge 5'              # a declared build tool
#   find . -exec gh pr merge 5 \;
#
# The merge is the human's gate — the ONE thing the whole delegation model
# reserves — so it has to be enforced where the entire command string is
# visible. That is here. Enumerating interpreters in the allow-rule policy
# (lib/common.sh fac_tool_allow_rule) is a useful narrowing but can never be
# complete; this check does not care which program is being run.
#
# TRADE-OFF, deliberate: matching anywhere means a command that merely MENTIONS
# one of these in an argument (a PR body documenting `gh pr merge`) is blocked
# too. That is the fail-closed direction, the sequences are specific enough that
# prose rarely trips them, and the message tells the author to reword. Silently
# allowing a wrapped merge is not an acceptable alternative.
if printf '%s' "$cmd" | grep -Eq 'gh[[:space:]]+pr[[:space:]]+merge([[:space:]]|$)'; then
  block "'gh pr merge' is the human's gate and is refused no matter how it is invoked (directly, or wrapped in awk/timeout/find/a shell). If you are only MENTIONING it in a PR body or comment, reword it (e.g. 'merge the PR')."
fi
if printf '%s' "$cmd" | grep -Eq 'gh[[:space:]]+repo[[:space:]]+delete([[:space:]]|$)'; then
  block "'gh repo delete' is refused no matter how it is invoked. If you are only MENTIONING it, reword it."
fi
# Force / delete pushes: `push` followed — across any run of intervening
# arguments, but not past a command separator — by a force or delete flag, or a
# `+refspec` force. Covers the spellings lib/permissions.sh documents as NOT
# prefix-expressible (`git push origin main --force`, and any `git -C dir push`
# form), and covers them under a wrapper too.
# The trailing boundary is "any character that cannot continue a flag name" (not
# just space/=/end) so a wrapped spelling still matches — inside
# `awk 'BEGIN{system("git push origin main --force")}'` the flag is followed by a
# quote, which an end-anchored boundary missed. --force-with-lease is listed
# before --force so the longer flag wins its own match.
# `push` is word-anchored (a non-word char before, whitespace after) so a command
# that merely CONTAINS the substring — `npm run push-docs -- -f` — is not caught.
if printf '%s' "$cmd" | grep -Eq '(^|[^A-Za-z0-9_-])push([[:space:]]+[^[:space:];&|]+)*[[:space:]]+(--force-with-lease|--force|--delete|-f|-d)([^A-Za-z0-9_-]|$)'; then
  block "a force/delete push is refused (protect the base branch server-side too). If you are only MENTIONING it, reword it."
fi
if printf '%s' "$cmd" | grep -Eq '(^|[^A-Za-z0-9_-])push([[:space:]]+[^[:space:];&|]+)*[[:space:]]+\+[A-Za-z0-9._/-]+:'; then
  block "a '+refspec' force push is refused. If you are only MENTIONING it, reword it."
fi

# GitHub-touching invocation? (word-boundary: start or any non-word char
# before, so `;`, `&&`, `|`, `$(`, backticks, quotes, newlines, and path
# prefixes like /usr/local/bin/gh are all caught.) Only gh / ai-gh-open-pr /
# `ai-gh open[-pr]` count. `git push` is deliberately NOT matched here: push
# containment lives in the permission grant (origin-scoped), so a benign
# command whose ARG TEXT merely contains "git push" is never mis-flagged, and
# `git -C dir push URL` spellings the hook couldn't reliably parse are handled
# by the grant instead.
if ! printf '%s' "$cmd" | grep -Eq '(^|[^[:alnum:]_.-])(gh[[:space:]]|ai-gh-open-pr([[:space:]]|$)|ai-gh[[:space:]]+open(-pr)?([[:space:]]|$))'; then
  exit 0
fi

# Both axes trust gh's config dir + credentials + default repo, so an inline
# override of any identity/config/target env in front of the gh invocation would
# let gh act as a different account, read a different hosts.yml, or target a
# different repo than this hook validated. gh honors BOTH token spellings
# (GH_TOKEN and GITHUB_TOKEN, and the *_ENTERPRISE_TOKEN pair), GH_REPO (target
# repo, defeats WHERE with no --repo flag), and GH_CONFIG_DIR/GH_HOST/HOME/
# XDG_CONFIG_HOME (config dir). Match ONLY a real command-position env assignment
# — at a command boundary (start / after ;&|(){), an optional `env`, and an
# optional chain of leading `VAR=val ` assignments, then the guarded var= — so a
# token that merely appears inside an argument value (`--title "document HOME= …"`,
# a `--body` mentioning `GH_TOKEN=…`) is NOT mistaken for an override. Any real
# leading assignment of these is always an override attempt here, so block it.
#
# THREE gaps closed here (all reproduced against the previous pattern):
#   1. The boundary class omitted the backtick and `$`, although the gh-detector
#      immediately below deliberately treats both as boundaries. So
#      `gh pr view 1 -q "` + GH_TOKEN=… gh api … + `"` slipped past — and that
#      spelling prefix-matches the granted Bash(gh pr view:*), so it really ran.
#   2. `(env[[:space:]]+)?` allowed no options, so `env -i GH_TOKEN=… gh …` and
#      `env -u FOO GH_TOKEN=… gh …` never reached the guarded var.
#   3. The chain element's value class could not span a quoted value containing
#      a space, so `FOO="a b" GH_TOKEN=… gh …` stopped the walk.
# (2) and (3) are defence in depth — those spellings start with `env`/an
# assignment and match no allow rule — but (1) was directly reachable.
if printf '%s' "$cmd" | grep -Eq '(^|[;&|(){}$`])[[:space:]]*(env([[:space:]]+-[^[:space:]]+([[:space:]]+[^-][^[:space:]]*)?)*[[:space:]]+)?([A-Za-z_][A-Za-z0-9_]*=("[^"]*"|'"'"'[^'"'"']*'"'"'|[^[:space:];&|]*)[[:space:]]+)*(GH_TOKEN|GITHUB_TOKEN|GH_ENTERPRISE_TOKEN|GITHUB_ENTERPRISE_TOKEN|GH_CONFIG_DIR|GH_HOST|GH_ENTERPRISE_HOST|GH_REPO|XDG_CONFIG_HOME|HOME)='; then
  block "refusing a gh invocation with an inline identity/config/target override (GH_TOKEN / GITHUB_TOKEN / GH_CONFIG_DIR / GH_HOST / GH_REPO / XDG_CONFIG_HOME / HOME=…); run gh without it so the WHO/WHERE pin holds."
fi

# Carve-out: the WHOLE command is a single `gh auth status|switch` invocation
# (no `;`, `&`, `|`, or substitution that could smuggle a second command). Only
# a SINGLE-line command qualifies — a multi-line cmd whose first line is
# `gh auth status` must still get full WHO/WHERE checks on its later lines, so
# the moment the command contains a newline we skip the carve-out and fall
# through to the full two-axis guard.
newline='
'
case "$cmd" in
  *"$newline"*) : ;;
  *)
    if printf '%s' "$cmd" | grep -Eq '^[[:space:]]*gh[[:space:]]+auth[[:space:]]+(status|switch)([^;&|`$]*)$'; then
      exit 0
    fi
    ;;
esac

# --- WHO: active account must be $WANT ---------------------------------------
# Resolve the pinned account WITHOUT baking it into this (committed) file: an
# explicit GH_GUARD_USER wins (tests / one-offs); else the operator's
# machine-local default seeded by install.sh / factory-init at
# $XDG_CONFIG_HOME/app-factory/account (UNCOMMITTED — keep this path in sync with
# lib/common.sh fac_account_file + install.sh); else the optional baked
# FAC_ACCOUNT_DEFAULT (empty for a factory-init'd repo, so no username is
# committed). An empty WANT fails closed rather than matching an empty active.
WANT="${GH_GUARD_USER:-}"
if [ -z "$WANT" ]; then
  WANT="$(head -n1 "${XDG_CONFIG_HOME:-$HOME/.config}/app-factory/account" 2>/dev/null | tr -d '[:space:]')"
fi
WANT="${WANT:-${FAC_ACCOUNT_DEFAULT:-}}"
if [ -z "$WANT" ]; then
  block "no pinned gh account configured — set one via install.sh, factory-init, or GH_GUARD_USER. Refusing to run gh unguarded."
fi
# Read the pinned user from the github.com block of hosts.yml, honoring
# GH_CONFIG_DIR then $XDG_CONFIG_HOME (gh resolves the config dir as
# GH_CONFIG_DIR -> $XDG_CONFIG_HOME/gh -> $HOME/.config/gh) and scoping the parse
# to the github.com: top-level key so a multi-host config can't surface another
# host's user. An empty active still blocks (fail closed). This requires a
# file-based `gh auth login`: a token-env (GH_TOKEN) CI setup with no `user:` in
# hosts.yml reads empty and blocks (fail closed).
#
# This is deliberately the FAST LABEL CHECK — a local file read, no network. The
# label is what gh recorded for the credential, and in principle it can disagree
# with the token's real identity (`gh api /user`); the authoritative check is
# therefore NOT done here. This hook runs on EVERY gh invocation in every lane,
# so a `gh api /user` round-trip per command would add latency to the whole run
# for an answer that cannot change mid-run. bin/factory-doctor verifies the real
# token identity against the pin ONCE per run, before any lane starts, and hard-
# fails there — so by the time this hook runs, label == identity == pin has
# already been established. Keep this path label-only and network-free.
active="$(awk '
  /^[^[:space:]]/ { in_gh = ($0 ~ /^github\.com:/) }
  in_gh && /^[[:space:]]+user:/ { print $2; exit }
' "${GH_CONFIG_DIR:-${XDG_CONFIG_HOME:-$HOME/.config}/gh}/hosts.yml" 2>/dev/null)"
if [ "$active" != "$WANT" ]; then
  block "active gh account is \"${active:-unknown}\", but GitHub here must run as \"$WANT\". Run \`gh auth switch -u $WANT\` first (switch back afterwards if needed)."
fi

# --- WHERE: the target repo must be the allowlisted repo ----------------------
# Was an explicit --repo/-R selector given at all? If so we must resolve it and
# never fall through to cwd-trust (fail closed when the caller named a repo).
repo_flag_seen=""
# `gh` uses pflag, which accepts the short flag glued to its value (`-Rowner/repo`)
# as well as separated (`-R owner/repo`), `=`-joined (`-R=owner/repo`), and the
# long `--repo` forms. Match the glued form too (`-R` optionally followed by
# `=`/space, then a value-start char) so it can't slip past to cwd-trust — the
# long form still requires a `=`/space separator.
if printf '%s' "$cmd" | grep -Eq -- '(--repo(=|[[:space:]])|-R(=|[[:space:]])?["'"'"']?[A-Za-z0-9_])'; then
  repo_flag_seen=1
fi

# 1. Explicit references: every --repo/-R value (glued `-Rx/y`, separated,
#    `=`-joined; surrounding single/double quotes stripped, so `--repo="x/y"`
#    and `-R"x/y"` can't slip past the matcher) and every github.com URL in the
#    command must match the allowlist.
flag_refs="$(printf '%s' "$cmd" | grep -oE -- '(--repo(=| )|-R(=| )?)["'"'"']?[^ ;&|"'"'"']+' 2>/dev/null | sed -E -e 's/^(--repo(=| )|-R(=| )?)//' -e 's/^["'"'"']+//' -e 's/["'"'"']+$//')"
# URL refs are extracted from the command with PROSE-CARRYING OPTION VALUES
# REMOVED. Unscoped, this grep read every github.com URL anywhere in the command
# as a target, so a PR body citing an upstream issue or a dependency's README
# ("see https://github.com/vendor/lib/issues/3") blocked the lane — AFTER the
# build and commits had landed, and a denial is the escalation signal, so a
# successful ticket got reported flagged. That is the same over-block class
# already fixed for `repos/x/y` by scoping api_refs below; URL refs were missed.
# Strip --body/--body-file/--title/-b/-t values (quoted or bare) first, then
# extract. A URL that is a real target (a --repo value or a bare positional)
# survives the strip and is still checked.
scan_cmd="$(printf '%s' "$cmd" | sed -E 's/(--body-file|--body|--title|--notes|-b|-t)([[:space:]]+|=)("[^"]*"|'"'"'[^'"'"']*'"'"'|[^[:space:]]*)/\1 /g')"
url_refs="$(printf '%s' "$scan_cmd" | grep -oE 'github\.com[:/][A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+' 2>/dev/null | sed -E 's#^github\.com[:/]##')"
# Positional repo references carrying no --repo flag and no github.com URL:
#   `gh api [/]repos/OWNER/REPO…` (the general cross-repo surface, incl. DELETE)
#   and `gh repo <sub> OWNER/REPO` (clone/view/fork/rename/…). Extraction is
#   SCOPED to the subcommand — api refs only from a `gh api` command, and only
#   the OWNER/REPO in the `gh repo <sub> OWNER/REPO` positional slot — so an
#   incidental `repos/x/y` / `owner/repo` token elsewhere in the command (a PR
#   body, a chained `npm i some/pkg`) is NOT mistaken for a target and over-
#   blocked. (`gh api graphql` and api paths with no `repos/OWNER/REPO` segment
#   carry no parseable target and still fall to cwd-trust — a documented residual.)
api_refs=""
if printf '%s' "$cmd" | grep -Eq '(^|[^[:alnum:]_.-])gh[[:space:]]+api[[:space:]]'; then
  api_refs="$(printf '%s' "$cmd" | grep -oE 'repos/[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+' 2>/dev/null | sed -E 's#^repos/##')"
fi
# The positional slot is located AFTER any run of option tokens (each optionally
# followed by its value), so a flag between the subcommand and the slug can no
# longer hide the target: `gh repo clone --depth 1 evil/thing`,
# `gh repo fork --org acme evil/thing` and `gh repo view --json name evil/thing`
# previously produced NO match, no --repo flag and no URL, and so fell through
# to cwd-trust — allowing the foreign-repo operation whenever the lane's cwd was
# the allowlisted repo. Extraction stays SCOPED to this one positional slot (not
# "every slug-shaped token in the command") so an unrelated `npm i some/pkg`
# chained after an allowlisted `gh repo clone` is still not mistaken for a target.
gh_repo_refs="$(printf '%s' "$cmd" | grep -oE '(^|[^[:alnum:]_.-])gh[[:space:]]+repo[[:space:]]+[A-Za-z-]+([[:space:]]+-[^[:space:]]+([[:space:]]+[^-][^[:space:];&|]*)?)*[[:space:]]+["'"'"']?[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+' 2>/dev/null | sed -E 's#.*[[:space:]]["'"'"']?([A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+)$#\1#')"
refs="$(printf '%s\n%s\n%s\n%s\n' "$flag_refs" "$url_refs" "$api_refs" "$gh_repo_refs")"
explicit_ok=""
while IFS= read -r ref; do
  [ -n "$ref" ] || continue
  # Normalize a URL-spelled ref down to OWNER/REPO before comparing. Refs are
  # compared as bare slugs, so `--repo https://github.com/OWNER/REPO` — a legal
  # gh spelling for the ALLOWED repo — was blocked as "outside the allowed repo".
  ref="${ref%.git}"
  ref="${ref#https://}"; ref="${ref#http://}"; ref="${ref#git@}"
  ref="${ref#github.com/}"; ref="${ref#github.com:}"
  if printf '%s' "$ref" | grep -Eq "^${ALLOWED_REPOS_RE}$"; then
    explicit_ok=1
  else
    block "target \"$ref\" is outside the allowed repo ($ALLOWED_REPOS_HUMAN)."
  fi
done <<EOF_REFS
$refs
EOF_REFS
# A named ref (flag / URL / positional) resolved and is allowlisted -> allow.
# Known limitation (shared with the --repo short-circuit): in a COMPOUND command
# that names an allowlisted repo AND then `cd`s elsewhere before a second gh
# (`gh repo clone acme/widget && cd /other && gh …`), this exits on the first
# ref and does not re-check the second gh's cwd. The WHO pin, the origin-scoped
# push grant, and server-side branch protection remain the backstops there.
[ -n "$explicit_ok" ] && exit 0

# An explicit --repo/-R flag was present but no usable ref was parsed: block
# rather than silently trusting the cwd origin.
if [ -n "$repo_flag_seen" ]; then
  block "a --repo/-R flag was given but its value could not be parsed; refusing to fall through to directory trust ($ALLOWED_REPOS_HUMAN)."
fi

# 2. No explicit reference: resolve the effective directory — a leading
#    `cd <path> &&` wins over the hook cwd — and require the origin remote to be
#    the allowlisted repo. (.cwd is only needed here, so extract it now — the
#    common path spawns one jq, not two.)
if [ "$have_jq" = "1" ]; then
  hook_cwd="$(printf '%s' "$raw" | jq -r '.cwd // empty' 2>/dev/null)"
else
  hook_cwd=""
fi
dir="$hook_cwd"
# Find every cwd change (`cd`/`pushd`) that sits at a real command boundary:
# start-of-string (optionally after leading whitespace) or a separator
# (`;`/`&`/`|`, or a subshell/brace-group opener `(`/`)`/`{`/`}`, optionally
# followed by whitespace). The last one wins — that is the effective cwd the
# following gh will run in. Anchoring on a *shell* boundary (never bare
# whitespace) matters twice over: (a) a plain `case cd\ *)` catches only
# literal-prefix `cd `, so leading whitespace (`\tcd /evil && gh …`), interior
# cd (`pwd && cd /other && gh …`), `pushd /other && gh …`, or a subshell
# (`(cd /other && gh …)`) / brace group (`{ cd /other; gh …; }`) would sail past
# — that's the WHERE bypass we are closing; (b) if we treated ANY whitespace as
# a boundary, a decoy inside a quoted string (`cd /evil && echo "cd /allowed" &&
# gh …`) would be picked as the "last" cd and trust the wrong dir. Boundary-only
# avoids both. (String-parsing shell is best-effort: an unrecognized cwd change
# fails safe to the allowlisted hook cwd, never to an attacker dir.)
d="$(printf '%s' "$cmd" | grep -oE '(^[[:space:]]*|[;&|(){}][[:space:]]*)(cd|pushd)[[:space:]]+[^ ;&|]+' 2>/dev/null | sed -nE 's/.*(cd|pushd)[[:space:]]+([^ ;&|]+).*/\2/p' | tail -n 1)"
if [ -n "$d" ]; then
  # Strip surrounding quotes so `cd "path"` resolves cleanly.
  d="${d#\"}"; d="${d%\"}"; d="${d#\'}"; d="${d%\'}"
  dir="$d"
fi
[ -n "$dir" ] || dir="$PWD"
url="$(git -C "$dir" remote get-url origin 2>/dev/null)"
url="${url%.git}"
if [ -z "$url" ]; then
  block "cannot determine the target repo (no --repo flag, and \"$dir\" has no git origin remote). Pass --repo $ALLOWED_REPOS_HUMAN or run from inside that repo."
fi
# Require a `:` or `/` boundary before the owner so a malicious origin like
# `host:evilOWNER/REPO` can't suffix-match the allowlisted `OWNER/REPO`.
if ! printf '%s' "$url" | grep -Eq "[:/]${ALLOWED_REPOS_RE}$"; then
  block "the repo at \"$dir\" (git origin: $url) is outside the allowed repo ($ALLOWED_REPOS_HUMAN)."
fi
exit 0
