#!/usr/bin/env bash
# gh-account-guard.sh — PreToolUse hook guarding GitHub actions in THIS repo,
# on two axes:
#   WHO   — gh may only act as the pinned account (resolved at runtime; see
#           the WHO block — never baked into this committed file).
#   WHERE — gh may only touch the one allowlisted repo (baked below).
#
# Generated by app-factory's factory-init and SELF-CONTAINED: it ships inside
# this repo and depends on nothing outside it. GH_GUARD_USER overrides the
# account for tests. Exit 0 = proceed to normal permission evaluation; 2 = block.
set -uo pipefail

FAC_ACCOUNT_DEFAULT=''
ALLOWED_REPOS_RE='abbasihsn/factory-console'
ALLOWED_REPOS_HUMAN='abbasihsn/factory-console'

raw="$(cat)"
# Fast pre-filter: the guard only cares about gh-touching invocations, so a
# payload without any "gh" substring can't match the gh-detector below. Skip
# the jq spawn entirely on those (the >95% of Bash calls that never touch gh)
# to keep the PreToolUse hot path cheap. Downstream matching stays authoritative.
case "$raw" in
  *gh*) ;;
  *) exit 0 ;;
esac
if command -v jq >/dev/null 2>&1; then
  have_jq=1
  cmd="$(printf '%s' "$raw" | jq -r '.tool_input.command // empty' 2>/dev/null)"
else
  # jq missing: fail CLOSED for gh-shaped input rather than silently unguarded.
  have_jq=0
  cmd="$raw"
fi
[ -n "$cmd" ] || exit 0

block() { printf 'GitHub action blocked: %s\n' "$1" >&2; exit 2; }

# GitHub-touching invocation? (word-boundary: start or any non-word char
# before, so `;`, `&&`, `|`, `$(`, backticks, quotes, newlines, and path
# prefixes like /usr/local/bin/gh are all caught.) Only gh / ai-gh-open-pr /
# `ai-gh open[-pr]` count. `git push` is deliberately NOT matched here: push
# containment lives in the permission grant (origin-scoped), so a benign
# command whose ARG TEXT merely contains "git push" is never mis-flagged, and
# `git -C dir push URL` spellings the hook couldn't reliably parse are handled
# by the grant instead.
if ! printf '%s' "$cmd" | grep -Eq '(^|[^[:alnum:]_.-])(gh[[:space:]]|ai-gh-open-pr([[:space:]]|$)|ai-gh[[:space:]]+open(-pr)?([[:space:]]|$))'; then
  exit 0
fi

# Both axes trust gh's config dir + credentials + default repo, so an inline
# override of any identity/config/target env in front of the gh invocation would
# let gh act as a different account, read a different hosts.yml, or target a
# different repo than this hook validated. gh honors BOTH token spellings
# (GH_TOKEN and GITHUB_TOKEN, and the *_ENTERPRISE_TOKEN pair), GH_REPO (target
# repo, defeats WHERE with no --repo flag), and GH_CONFIG_DIR/GH_HOST/HOME/
# XDG_CONFIG_HOME (config dir). Match ONLY a real command-position env assignment
# — at a command boundary (start / after ;&|(){), an optional `env`, and an
# optional chain of leading `VAR=val ` assignments, then the guarded var= — so a
# token that merely appears inside an argument value (`--title "document HOME= …"`,
# a `--body` mentioning `GH_TOKEN=…`) is NOT mistaken for an override. Any real
# leading assignment of these is always an override attempt here, so block it.
if printf '%s' "$cmd" | grep -Eq '(^|[;&|(){])[[:space:]]*(env[[:space:]]+)?([A-Za-z_][A-Za-z0-9_]*=[^[:space:];&|]*[[:space:]]+)*(GH_TOKEN|GITHUB_TOKEN|GH_ENTERPRISE_TOKEN|GITHUB_ENTERPRISE_TOKEN|GH_CONFIG_DIR|GH_HOST|GH_ENTERPRISE_HOST|GH_REPO|XDG_CONFIG_HOME|HOME)='; then
  block "refusing a gh invocation with an inline identity/config/target override (GH_TOKEN / GITHUB_TOKEN / GH_CONFIG_DIR / GH_HOST / GH_REPO / XDG_CONFIG_HOME / HOME=…); run gh without it so the WHO/WHERE pin holds."
fi

# Carve-out: the WHOLE command is a single `gh auth status|switch` invocation
# (no `;`, `&`, `|`, or substitution that could smuggle a second command). Only
# a SINGLE-line command qualifies — a multi-line cmd whose first line is
# `gh auth status` must still get full WHO/WHERE checks on its later lines, so
# the moment the command contains a newline we skip the carve-out and fall
# through to the full two-axis guard.
newline='
'
case "$cmd" in
  *"$newline"*) : ;;
  *)
    if printf '%s' "$cmd" | grep -Eq '^[[:space:]]*gh[[:space:]]+auth[[:space:]]+(status|switch)([^;&|`$]*)$'; then
      exit 0
    fi
    ;;
esac

# --- WHO: active account must be $WANT ---------------------------------------
# Resolve the pinned account WITHOUT baking it into this (committed) file: an
# explicit GH_GUARD_USER wins (tests / one-offs); else the operator's
# machine-local default seeded by install.sh / factory-init at
# $XDG_CONFIG_HOME/app-factory/account (UNCOMMITTED — keep this path in sync with
# lib/common.sh fac_account_file + install.sh); else the optional baked
# FAC_ACCOUNT_DEFAULT (empty for a factory-init'd repo, so no username is
# committed). An empty WANT fails closed rather than matching an empty active.
WANT="${GH_GUARD_USER:-}"
if [ -z "$WANT" ]; then
  WANT="$(head -n1 "${XDG_CONFIG_HOME:-$HOME/.config}/app-factory/account" 2>/dev/null | tr -d '[:space:]')"
fi
WANT="${WANT:-${FAC_ACCOUNT_DEFAULT:-}}"
if [ -z "$WANT" ]; then
  block "no pinned gh account configured — set one via install.sh, factory-init, or GH_GUARD_USER. Refusing to run gh unguarded."
fi
# Read the pinned user from the github.com block of hosts.yml, honoring
# GH_CONFIG_DIR then $XDG_CONFIG_HOME (gh resolves the config dir as
# GH_CONFIG_DIR -> $XDG_CONFIG_HOME/gh -> $HOME/.config/gh) and scoping the parse
# to the github.com: top-level key so a multi-host config can't surface another
# host's user. An empty active still blocks (fail closed). This requires a
# file-based `gh auth login`: a token-env (GH_TOKEN) CI setup with no `user:` in
# hosts.yml reads empty and blocks (fail closed).
active="$(awk '
  /^[^[:space:]]/ { in_gh = ($0 ~ /^github\.com:/) }
  in_gh && /^[[:space:]]+user:/ { print $2; exit }
' "${GH_CONFIG_DIR:-${XDG_CONFIG_HOME:-$HOME/.config}/gh}/hosts.yml" 2>/dev/null)"
if [ "$active" != "$WANT" ]; then
  block "active gh account is \"${active:-unknown}\", but GitHub here must run as \"$WANT\". Run \`gh auth switch -u $WANT\` first (switch back afterwards if needed)."
fi

# --- WHERE: the target repo must be the allowlisted repo ----------------------
# Was an explicit --repo/-R selector given at all? If so we must resolve it and
# never fall through to cwd-trust (fail closed when the caller named a repo).
repo_flag_seen=""
# `gh` uses pflag, which accepts the short flag glued to its value (`-Rowner/repo`)
# as well as separated (`-R owner/repo`), `=`-joined (`-R=owner/repo`), and the
# long `--repo` forms. Match the glued form too (`-R` optionally followed by
# `=`/space, then a value-start char) so it can't slip past to cwd-trust — the
# long form still requires a `=`/space separator.
if printf '%s' "$cmd" | grep -Eq -- '(--repo(=|[[:space:]])|-R(=|[[:space:]])?["'"'"']?[A-Za-z0-9_])'; then
  repo_flag_seen=1
fi

# 1. Explicit references: every --repo/-R value (glued `-Rx/y`, separated,
#    `=`-joined; surrounding single/double quotes stripped, so `--repo="x/y"`
#    and `-R"x/y"` can't slip past the matcher) and every github.com URL in the
#    command must match the allowlist.
flag_refs="$(printf '%s' "$cmd" | grep -oE -- '(--repo(=| )|-R(=| )?)["'"'"']?[^ ;&|"'"'"']+' 2>/dev/null | sed -E -e 's/^(--repo(=| )|-R(=| )?)//' -e 's/^["'"'"']+//' -e 's/["'"'"']+$//')"
url_refs="$(printf '%s' "$cmd" | grep -oE 'github\.com[:/][A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+' 2>/dev/null | sed -E 's#^github\.com[:/]##')"
# Positional repo references carrying no --repo flag and no github.com URL:
#   `gh api [/]repos/OWNER/REPO…` (the general cross-repo surface, incl. DELETE)
#   and `gh repo <sub> OWNER/REPO` (clone/view/fork/rename/…). Extraction is
#   SCOPED to the subcommand — api refs only from a `gh api` command, and only
#   the OWNER/REPO in the `gh repo <sub> OWNER/REPO` positional slot — so an
#   incidental `repos/x/y` / `owner/repo` token elsewhere in the command (a PR
#   body, a chained `npm i some/pkg`) is NOT mistaken for a target and over-
#   blocked. (`gh api graphql` and api paths with no `repos/OWNER/REPO` segment
#   carry no parseable target and still fall to cwd-trust — a documented residual.)
api_refs=""
if printf '%s' "$cmd" | grep -Eq '(^|[^[:alnum:]_.-])gh[[:space:]]+api[[:space:]]'; then
  api_refs="$(printf '%s' "$cmd" | grep -oE 'repos/[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+' 2>/dev/null | sed -E 's#^repos/##')"
fi
gh_repo_refs="$(printf '%s' "$cmd" | grep -oE '(^|[^[:alnum:]_.-])gh[[:space:]]+repo[[:space:]]+[A-Za-z-]+[[:space:]]+["'"'"']?[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+' 2>/dev/null | sed -E 's#.*[[:space:]]["'"'"']?([A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+)$#\1#')"
refs="$(printf '%s\n%s\n%s\n%s\n' "$flag_refs" "$url_refs" "$api_refs" "$gh_repo_refs")"
explicit_ok=""
while IFS= read -r ref; do
  [ -n "$ref" ] || continue
  ref="${ref%.git}"
  if printf '%s' "$ref" | grep -Eq "^${ALLOWED_REPOS_RE}$"; then
    explicit_ok=1
  else
    block "target \"$ref\" is outside the allowed repo ($ALLOWED_REPOS_HUMAN)."
  fi
done <<EOF_REFS
$refs
EOF_REFS
# A named ref (flag / URL / positional) resolved and is allowlisted -> allow.
# Known limitation (shared with the --repo short-circuit): in a COMPOUND command
# that names an allowlisted repo AND then `cd`s elsewhere before a second gh
# (`gh repo clone acme/widget && cd /other && gh …`), this exits on the first
# ref and does not re-check the second gh's cwd. The WHO pin, the origin-scoped
# push grant, and server-side branch protection remain the backstops there.
[ -n "$explicit_ok" ] && exit 0

# An explicit --repo/-R flag was present but no usable ref was parsed: block
# rather than silently trusting the cwd origin.
if [ -n "$repo_flag_seen" ]; then
  block "a --repo/-R flag was given but its value could not be parsed; refusing to fall through to directory trust ($ALLOWED_REPOS_HUMAN)."
fi

# 2. No explicit reference: resolve the effective directory — a leading
#    `cd <path> &&` wins over the hook cwd — and require the origin remote to be
#    the allowlisted repo. (.cwd is only needed here, so extract it now — the
#    common path spawns one jq, not two.)
if [ "$have_jq" = "1" ]; then
  hook_cwd="$(printf '%s' "$raw" | jq -r '.cwd // empty' 2>/dev/null)"
else
  hook_cwd=""
fi
dir="$hook_cwd"
# Find every cwd change (`cd`/`pushd`) that sits at a real command boundary:
# start-of-string (optionally after leading whitespace) or a separator
# (`;`/`&`/`|`, or a subshell/brace-group opener `(`/`)`/`{`/`}`, optionally
# followed by whitespace). The last one wins — that is the effective cwd the
# following gh will run in. Anchoring on a *shell* boundary (never bare
# whitespace) matters twice over: (a) a plain `case cd\ *)` catches only
# literal-prefix `cd `, so leading whitespace (`\tcd /evil && gh …`), interior
# cd (`pwd && cd /other && gh …`), `pushd /other && gh …`, or a subshell
# (`(cd /other && gh …)`) / brace group (`{ cd /other; gh …; }`) would sail past
# — that's the WHERE bypass we are closing; (b) if we treated ANY whitespace as
# a boundary, a decoy inside a quoted string (`cd /evil && echo "cd /allowed" &&
# gh …`) would be picked as the "last" cd and trust the wrong dir. Boundary-only
# avoids both. (String-parsing shell is best-effort: an unrecognized cwd change
# fails safe to the allowlisted hook cwd, never to an attacker dir.)
d="$(printf '%s' "$cmd" | grep -oE '(^[[:space:]]*|[;&|(){}][[:space:]]*)(cd|pushd)[[:space:]]+[^ ;&|]+' 2>/dev/null | sed -nE 's/.*(cd|pushd)[[:space:]]+([^ ;&|]+).*/\2/p' | tail -n 1)"
if [ -n "$d" ]; then
  # Strip surrounding quotes so `cd "path"` resolves cleanly.
  d="${d#\"}"; d="${d%\"}"; d="${d#\'}"; d="${d%\'}"
  dir="$d"
fi
[ -n "$dir" ] || dir="$PWD"
url="$(git -C "$dir" remote get-url origin 2>/dev/null)"
url="${url%.git}"
if [ -z "$url" ]; then
  block "cannot determine the target repo (no --repo flag, and \"$dir\" has no git origin remote). Pass --repo $ALLOWED_REPOS_HUMAN or run from inside that repo."
fi
# Require a `:` or `/` boundary before the owner so a malicious origin like
# `host:evilOWNER/REPO` can't suffix-match the allowlisted `OWNER/REPO`.
if ! printf '%s' "$url" | grep -Eq "[:/]${ALLOWED_REPOS_RE}$"; then
  block "the repo at \"$dir\" (git origin: $url) is outside the allowed repo ($ALLOWED_REPOS_HUMAN)."
fi
exit 0
