/**
 * DO NOT EDIT — regenerate with pnpm codegen
 *
 * Generated by openapi-typescript from the server's /api/v1/openapi.json.
 * Any manual edit is overwritten the next time `pnpm codegen` runs.
 */

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/api/v1/health": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe: ``{ok, version, projectRoot}`` (projectRoot null until T24).
         */
        readonly get: operations["health_api_v1_health_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/project": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Project
         * @description Return the discovered target :class:`Project` for the running console.
         *
         *     Reads the discovered root from ``request.app.state.project_root`` — a ``Path``
         *     ``create_app`` requires at boot — and returns ``adapter.load_project(root)``.
         *     Raises nothing itself: a ``ProjectNotFound`` from the adapter propagates to the
         *     registered domain-error handler, which maps it to the 404 envelope.
         */
        readonly get: operations["get_project_api_v1_project_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/tickets": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * List Tickets
         * @description Return the ticket summaries matching the ``status``/``track``/``milestone``/``q`` filters.
         *
         *     Loads the discovered project from ``request.app.state.project_root`` and
         *     delegates filtering to :class:`TicketService`; ``total`` is the number of
         *     matching items (there is no pagination in the MVP).
         */
        readonly get: operations["list_tickets_api_v1_tickets_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/tickets/{ticket_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Ticket
         * @description Return the full :class:`Ticket` for ``ticket_id`` with run-state resolved.
         *
         *     ``ticket_id`` is validated at the ``Path`` boundary against the shared
         *     :data:`TICKET_ID_PATTERN` (an invalid id becomes the ``invalid_ticket_id``
         *     400 envelope and never reaches the adapter). Loads the discovered project and
         *     delegates to :class:`TicketService`, whose ``TicketNotFound`` propagates to the
         *     domain-error handler as a 404 for an id absent from the manifest.
         */
        readonly get: operations["get_ticket_api_v1_tickets__ticket_id__get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        readonly HTTPValidationError: {
            /** Detail */
            readonly detail?: readonly components["schemas"]["ValidationError"][];
        };
        /**
         * Project
         * @description Resolved paths for one App Factory project, discovered per request.
         *
         *     ``roadmapPath`` and ``runStateDir`` are ``None`` when the corresponding file
         *     or directory is absent from the target project (both are optional in the
         *     project layout).
         */
        readonly Project: {
            /**
             * Rootpath
             * Format: path
             */
            readonly rootPath: string;
            /**
             * Ticketsmanifestpath
             * Format: path
             */
            readonly ticketsManifestPath: string;
            /**
             * Ticketsdir
             * Format: path
             */
            readonly ticketsDir: string;
            /** Roadmappath */
            readonly roadmapPath?: string | null;
            /** Runstatedir */
            readonly runStateDir?: string | null;
            /**
             * Discoveredat
             * Format: date-time
             */
            readonly discoveredAt: string;
        };
        /**
         * RunState
         * @description A ticket's run-state, derived by probing the factory run-state directory.
         *
         *     Subclasses ``str`` so a member compares and serializes as its string value
         *     (``RunState.todo == "todo"``); the value is the on-disk directory name.
         * @enum {string}
         */
        readonly RunState: "todo" | "in-flight" | "ready" | "merged" | "unknown";
        /**
         * Ticket
         * @description A manifest entry joined with its rendered ``.md`` body.
         *
         *     ``raw`` preserves the unmodified manifest entry — including fields this model
         *     does not name — for forward-compatibility with future factory versions.
         *     ``extra='forbid'`` governs the model's *own* fields; it does not restrict the
         *     contents of the ``raw`` mapping. ``runState`` defaults to
         *     :attr:`RunState.unknown` and is resolved per request by the service on the
         *     detail path (the manifest/enrichment build sites leave it at the default).
         */
        readonly Ticket: {
            /** Id */
            readonly id: string;
            /** Title */
            readonly title: string;
            /** Status */
            readonly status: string;
            /** Track */
            readonly track?: string | null;
            /** Milestone */
            readonly milestone?: string | null;
            /** @default unknown */
            readonly runState: components["schemas"]["RunState"];
            /** Dependson */
            readonly dependsOn?: readonly string[];
            /** Provides */
            readonly provides?: readonly string[];
            /** Files */
            readonly files?: readonly string[];
            /**
             * Filepath
             * Format: path
             */
            readonly filePath: string;
            /** Bodymarkdown */
            readonly bodyMarkdown: string;
            /** Bodyhtml */
            readonly bodyHtml: string;
            /** Raw */
            readonly raw: {
                readonly [key: string]: unknown;
            };
        };
        /**
         * TicketListResponse
         * @description Envelope for the tickets list: the matching summaries and their count.
         */
        readonly TicketListResponse: {
            /** Items */
            readonly items: readonly components["schemas"]["TicketSummary"][];
            /** Total */
            readonly total: number;
        };
        /**
         * TicketSummary
         * @description List-projection of a ticket for the tickets index view.
         *
         *     ``runState`` is resolved per request by probing the factory run-state
         *     directory; ``depCount`` / ``dependentCount`` come from reverse-indexing
         *     ``dependsOn`` across the manifest.
         */
        readonly TicketSummary: {
            /** Id */
            readonly id: string;
            /** Title */
            readonly title: string;
            /** Status */
            readonly status: string;
            /** Track */
            readonly track?: string | null;
            /** Milestone */
            readonly milestone?: string | null;
            readonly runState: components["schemas"]["RunState"];
            /** Depcount */
            readonly depCount: number;
            /** Dependentcount */
            readonly dependentCount: number;
        };
        /** ValidationError */
        readonly ValidationError: {
            /** Location */
            readonly loc: readonly (string | number)[];
            /** Message */
            readonly msg: string;
            /** Error Type */
            readonly type: string;
            /** Input */
            readonly input?: unknown;
            /** Context */
            readonly ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly health_api_v1_health_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly [key: string]: unknown;
                    };
                };
            };
        };
    };
    readonly get_project_api_v1_project_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    readonly list_tickets_api_v1_tickets_get: {
        readonly parameters: {
            readonly query?: {
                readonly status?: string | null;
                readonly track?: string | null;
                readonly milestone?: string | null;
                readonly q?: string | null;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["TicketListResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_ticket_api_v1_tickets__ticket_id__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly ticket_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Ticket"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
