/**
 * DO NOT EDIT — regenerate with pnpm codegen
 *
 * Generated by openapi-typescript from the server's /api/v1/openapi.json.
 * Any manual edit is overwritten the next time `pnpm codegen` runs.
 */

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/api/v1/project": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Project
         * @description Return the SELECTED target :class:`Project` for the running console.
         *
         *     ``root`` is resolved per request by
         *     :func:`~factory_console.api.deps.get_current_project_root`, so the project
         *     described is whichever one is currently selected. Raises nothing itself: a
         *     ``ProjectNotFound`` from the adapter maps to the 404 envelope and a selection
         *     failure to its ``409`` — both through the registered domain-error handler, so
         *     there is no error handling in this endpoint.
         */
        readonly get: operations["get_project_api_v1_project_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/tickets": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * List Tickets
         * @description Return the ticket summaries matching the ``status``/``track``/``milestone``/``q`` filters.
         *
         *     Loads the SELECTED project at the per-request ``root`` and delegates filtering
         *     to :class:`TicketService`; ``total`` is the number of matching items (there is
         *     no pagination in the MVP). Both blocking calls are awaited off the event loop.
         */
        readonly get: operations["list_tickets_api_v1_tickets_get"];
        readonly put?: never;
        /**
         * Create Ticket
         * @description Create the ticket described by ``payload``, or preview it when ``?dryRun=true``.
         *
         *     The status code follows the RESULT rather than the query flag: an apply reports
         *     ``201 Created``, a dry-run ``200 OK``, because a preview creates nothing and a
         *     ``201`` would tell the SPA (and any cache between them) that it did. Setting
         *     ``response.status_code`` overrides the route's declared default, which stays ``201``
         *     so that remains the documented success code.
         *
         *     Writes into the SELECTED project at the per-request ``root``; an unresolvable
         *     selection refuses with the named 409 before any port is touched. Delegates to
         *     :meth:`~factory_console.services.write_service.WriteService.create`, whose
         *     ``WriteConflict`` (409) propagates for an id that already exists. Both blocking calls
         *     are awaited off the event loop, under ``write_lock`` for their combined duration —
         *     they are one read-modify-write of the manifest, and that guard is what makes the
         *     duplicate-id ``WriteConflict`` above hold against a concurrent create of the same id.
         */
        readonly post: operations["create_ticket_api_v1_tickets_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/tickets/{ticket_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Ticket
         * @description Return the full :class:`Ticket` for ``ticket_id`` with run-state resolved.
         *
         *     ``ticket_id`` is validated at the ``Path`` boundary against the shared
         *     :data:`TICKET_ID_PATTERN` (an invalid id becomes the ``invalid_ticket_id``
         *     400 envelope and never reaches the adapter). Loads the SELECTED project at the
         *     per-request ``root`` and delegates to :class:`TicketService`, whose
         *     ``TicketNotFound`` propagates to the domain-error handler as a 404 for an id
         *     absent from the manifest. Both blocking calls are awaited off the event loop.
         */
        readonly get: operations["get_ticket_api_v1_tickets__ticket_id__get"];
        /**
         * Edit Ticket
         * @description Apply ``payload`` to ``ticket_id``, or preview the edit when ``?dryRun=true``.
         *
         *     Always ``200``: an edit creates no resource on either path. Edits the ticket in the
         *     SELECTED project at the per-request ``root``; an unresolvable selection refuses with
         *     the named 409 before any port is touched. Delegates to
         *     :meth:`~factory_console.services.write_service.WriteService.edit`, whose
         *     ``TicketNotFound`` (404) and ``TicketNotMutable`` (409, for a run-state outside the
         *     EDIT allowlist ``todo``/``unknown``) propagate to the registered handlers. Both
         *     blocking calls are awaited off the event loop, under ``write_lock`` for their combined
         *     duration — an edit rewrites the manifest from what the load observed, so it is the same
         *     read-modify-write the module docstring's create case describes.
         */
        readonly put: operations["edit_ticket_api_v1_tickets__ticket_id__put"];
        readonly post?: never;
        /**
         * Delete Ticket
         * @description Delete ``ticket_id``, or preview the delete when ``?dryRun=true``.
         *
         *     Always ``200`` with the uniform :class:`WriteResult` body rather than a bodiless
         *     ``204``, because the SPA renders the delete's diff in the same confirmation view as
         *     a create or an edit. Deletes from the SELECTED project at the per-request ``root``;
         *     an unresolvable selection refuses with the named 409 before any port is touched —
         *     the request whose fail-open would destroy a file in the wrong repository. Delegates
         *     to :meth:`~factory_console.services.write_service.WriteService.delete`, whose
         *     ``TicketNotFound`` (404) and ``TicketNotMutable`` (409) propagate to the registered
         *     handlers. Both blocking calls are awaited off the event loop, under ``write_lock`` for
         *     their combined duration — a delete rewrites the manifest from what the load observed,
         *     so it is the same read-modify-write the module docstring's create case describes.
         */
        readonly delete: operations["delete_ticket_api_v1_tickets__ticket_id__delete"];
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/tickets/{ticket_id}/deps": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Ticket Deps
         * @description Return the :class:`DepNeighborhood` for ``ticket_id``.
         *
         *     ``ticket_id`` is validated at the ``Path`` boundary against the shared
         *     :data:`TICKET_ID_PATTERN` (an invalid id becomes the ``invalid_ticket_id``
         *     400 envelope and never reaches the adapter). Loads the SELECTED project at the
         *     per-request ``root`` and delegates to :class:`DepsService`, whose
         *     ``TicketNotFound`` propagates to the domain-error handler as a 404 for an id
         *     absent from the manifest. Both blocking calls are awaited off the event loop.
         */
        readonly get: operations["get_ticket_deps_api_v1_tickets__ticket_id__deps_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/health": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Health
         * @description Return the liveness probe plus what the console currently has selected.
         *
         *     ``version`` is read from ``app.state``, where ``create_app`` stashed it at boot.
         *     The three selection fields come from :func:`_resolve_selection`, which resolves
         *     through the same seam every other endpoint uses but reports its failures instead
         *     of raising them — so this route answers ``200`` whether a project is selected, is
         *     selected and gone, or was never selected at all. It is the only project-scoped
         *     route with no 409 and no 503, by design; see the module docstring.
         */
        readonly get: operations["get_health_api_v1_health_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/roadmap": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Roadmap
         * @description Return the SELECTED project's full :class:`Roadmap`, or :class:`RoadmapAbsent`.
         *
         *     Loads the project at the per-request ``root`` and calls
         *     ``adapter.get_roadmap(project)``, returning the full :class:`Roadmap` — its
         *     ``bodyMarkdown``, ``bodyHtml``, and structured ``milestones[]`` — when the
         *     project has one, else :class:`RoadmapAbsent`. Does no error handling of its
         *     own: a ``ProjectNotFound`` from ``load_project``, a ``RoadmapUnreadable``
         *     (500) from ``adapter.get_roadmap``, and the selection seam's ``409``s all
         *     propagate to the registered domain-error handler, which renders the mapped
         *     envelope.
         */
        readonly get: operations["get_roadmap_api_v1_roadmap_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/search": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Search
         * @description Return the ranked :class:`SearchHit` s matching the full-text query ``q``.
         *
         *     ``q`` is required; a blank or whitespace-only value yields an empty result
         *     (``{items: [], total: 0}``) rather than a validation error. ``limit`` bounds
         *     the number of hits to ``ge=1``/``le=200`` (default 50) — an out-of-range value
         *     is rejected at the ``Query`` boundary as the ``validation_error`` 422 envelope
         *     and never reaches the service. Loads the SELECTED project at the per-request
         *     ``root`` and delegates ranking to :class:`SearchService`; ``total`` is the
         *     number of returned items. Both blocking calls are awaited off the event loop.
         */
        readonly get: operations["search_api_v1_search_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/graph": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Graph
         * @description Return the SELECTED project's whole-project dependency :class:`TicketGraph`.
         *
         *     ``root`` is resolved per request by
         *     :func:`~factory_console.api.deps.get_current_project_root`; the project is then
         *     loaded and handed to :class:`GraphService`. Returns the ``TicketGraph`` domain
         *     model directly so OpenAPI publishes its nodes+edges shape. Raises nothing itself:
         *     a ``ProjectNotFound`` from the adapter maps to the 404 envelope and a selection
         *     failure to its ``409``, both through the registered domain-error handler.
         *
         *     ``functools.partial`` binds the arguments for both offloads because ``run_sync``
         *     passes positionals only and takes no keywords.
         */
        readonly get: operations["get_graph_api_v1_graph_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/events": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Events
         * @description Stream live :class:`ChangeEvent`s to the client as ``text/event-stream``.
         *
         *     Delegates the entire stream body to
         *     :func:`~factory_console.services.events_service.sse_event_stream`, which yields
         *     the initial ``ready`` frame, an ``event: change`` frame per file change while
         *     the resolved ``watcher`` is present, and periodic ``: keepalive`` comments,
         *     releasing the watcher subscription when the client disconnects. The
         *     ``no-cache`` / ``X-Accel-Buffering: no`` headers keep the long-lived stream
         *     un-cached and un-buffered by any intermediary.
         *
         *     ``generation`` is read FIRST, then ``watcher`` — both off the same ``supervisor``,
         *     sequentially in this body, never as two separate ``Depends`` (see the module
         *     docstring for why the order and the single source matter). ``watcher`` is whichever
         *     was live at that instant and is not re-resolved afterwards: a stream is bound to the
         *     project selected at connect (see the module docstring for why). What the stream
         *     re-reads instead is ``supervisor.generation()``, compared on each heartbeat tick
         *     against the value captured here: once it moves, this connection's watcher has been
         *     replaced, so the stream emits a terminal ``event: stale`` frame and ends rather than
         *     heartbeating on a stopped watcher forever. The comparison is a pure integer read with
         *     no I/O, so the route stays non-blocking.
         *
         *     ``supervisor`` is typed non-optional because ``create_app`` ALWAYS binds one —
         *     a watcher-less app is a supervisor holding nothing, not an absent supervisor —
         *     so ``get_watcher_supervisor`` raises rather than degrading, exactly like the
         *     other wiring-bug dependencies. That raise is unreachable in a real app and
         *     changes no client-visible behaviour here.
         */
        readonly get: operations["events_api_v1_events_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/spend": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Spend
         * @description Return the SELECTED project's aggregated spend, or an explicit "no ledger" body.
         *
         *     Reads the ledger off the per-request ``root``. With no ledger the response is
         *     ``source.found: false`` over zeroed totals; with one, it is the aggregate of
         *     every entry that parsed, plus the line numbers and reasons of those that did
         *     not. A ledger that exists but could not be read at all is the third case, and
         *     says so with ``source.read: false`` rather than passing its zeroed totals off
         *     as a measurement. The ledger's ``excerpt`` and ``session_id`` are projected
         *     nowhere. The probe, the read, and the aggregation over what it returned all run
         *     together in one ``anyio.to_thread.run_sync`` hop, awaited off the event loop —
         *     see :func:`_load_spend`.
         */
        readonly get: operations["get_spend_api_v1_spend_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/runs": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * List Runs
         * @description Return one :class:`ProjectedRunRecord` per manifest ticket, in manifest order.
         *
         *     Loads the SELECTED project at the per-request ``root`` and delegates
         *     the whole composition to :class:`RunService` over the injected
         *     :class:`FileAdapter` and :class:`RunArtifactReader`. Both calls are synchronous and
         *     hit the disk, so both are awaited through ``anyio.to_thread.run_sync`` — the
         *     coroutine yields for the duration, and every other route (the SSE stream above all)
         *     keeps being served while this one reads. ``functools.partial`` binds the arguments
         *     because ``run_sync`` passes positionals only and takes no keywords.
         *
         *     ``total`` is the number of records, which is the manifest's ticket count and not a
         *     count of tickets that have artifacts — there is no filtering and NO PAGINATION, the
         *     same answer its sibling list endpoints give. That is a decision, not an omission:
         *     the list's length is the manifest's length, the manifest is a planning document an
         *     operator writes and reviews by hand (hundreds of entries at the outside, not
         *     millions), and it is already served whole by ``GET /api/v1/tickets``. Paging one of
         *     three list endpoints would split the envelope contract the SPA unwraps for all
         *     three, to bound a list nothing observed to be unbounded. What actually caps the
         *     cost is the offload above: the read is off the loop, so its size no longer stalls
         *     the rest of the app. Revisit if a real manifest ever makes the response slow — see
         *     ``ARCHITECTURE.md``'s Cross-cutting **Concurrency** bullet.
         *
         *     The service's records are projected through :meth:`ProjectedRunRecord.from_record`
         *     before they are counted or returned. ``total`` is unaffected by the narrowing — it
         *     is a count of RECORDS, one per manifest ticket, and the projection changes what a
         *     record discloses, never how many there are.
         */
        readonly get: operations["list_runs_api_v1_runs_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/projects": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * List Projects
         * @description Return every project the switcher offers, session row first, with its condition.
         *
         *     Delegates the whole composition to :func:`_list_rows` inside a SINGLE
         *     ``anyio.to_thread.run_sync`` hop — the selection read, the ``sqlite3`` query and the
         *     per-row ``stat``s together, never one hop per row. ``functools.partial`` binds the
         *     arguments because ``run_sync`` passes positionals only.
         *
         *     This route never fails over the selection: with nothing selected, every row simply
         *     reports ``selected: false``. That is the point of it — the listing is what a user
         *     browses in order to choose, so raising the 409s
         *     :func:`~factory_console.api.deps.get_current_project_root` raises would deny them the
         *     screen that fixes the condition. A :class:`RegistryUnreadable` from the store still
         *     propagates as its 503 through ``_read_registry``, which is the honest answer when the
         *     console cannot read its own table at all.
         *
         *     The condition probe is instantiated here rather than injected through ``app.state``.
         *     :class:`~factory_console.file_adapter.project_condition.RealProjectConditionProbe` is
         *     stateless, takes no arguments and caches nothing, and no DI seam for it exists yet;
         *     inventing one for a single call site would add app wiring this contract does not
         *     need. Tests reach the seam by overriding these dependencies or by pointing real
         *     ``tmp_path`` directories at the real probe, which is the more faithful test anyway.
         */
        readonly get: operations["list_projects_api_v1_projects_get"];
        readonly put?: never;
        /**
         * Add Project
         * @description Register ``payload.path`` and return the switcher row it becomes.
         *
         *     ``201`` with the created row rather than a bodiless ``201 + Location``: the SPA
         *     inserts the new row into an already-rendered dropdown, and the row carries three
         *     facts only the server holds (the minted id, the ``addedAt`` stamp and the probed
         *     ``condition``), so a client that got a URL back would immediately have to GET it.
         *
         *     **NOT idempotent, by design.** A second POST of the same directory is
         *     ``409 duplicate_project_path`` carrying the existing row's id, never a silent
         *     no-op — so the SPA can say "you already track this" and offer to switch to it,
         *     which a 200-with-the-old-row could not be distinguished from a fresh add.
         *
         *     Adding does NOT select. Registration and selection are separate acts, and conflating
         *     them would yank the board out from under an operator adding a second project while
         *     reading the first; the returned row therefore always reports ``selected: false``.
         *
         *     The whole body — canonicalise, discover, insert, probe — runs in ONE
         *     ``anyio.to_thread.run_sync`` hop, plain rather than through
         *     :func:`~factory_console.api.deps._read_registry` (see :func:`_register_project` for
         *     the order, the errors it lets through, and why only its ``registry.add_project`` step
         *     is wrapped in that 503 mapping rather than the whole hop).
         *
         *     Note that discovery WALKS UP from the given path, so registering a subdirectory of
         *     an App Factory project passes validation — and the row records the DISCOVERED root,
         *     not the subdirectory the caller typed, so two different spellings of one project
         *     resolve to the one row the ``UNIQUE`` index is meant to guarantee, instead of each
         *     inserting its own.
         */
        readonly post: operations["add_project_api_v1_projects_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/projects/current": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Current
         * @description Return the selected project, or ``selected: null`` with the named ``reason``.
         *
         *     A 200 in both cases, never a 404: having nothing selected is the ordinary state of a
         *     fresh console, and the SPA renders the reason as a prompt. The resolution — and the
         *     argument for why it reuses the selection seam's own servability probe rather than
         *     re-deriving one — is in :func:`_resolve_current`; like the listing, it runs in one
         *     ``anyio.to_thread.run_sync`` hop through ``_read_registry``, so a
         *     :class:`RegistryUnreadable` still surfaces as a 503.
         *
         *     Exactly one of the two fields is set, because the resolution returns exactly one of a
         *     row or a reason and each populates its own field.
         */
        readonly get: operations["get_current_api_v1_projects_current_get"];
        /**
         * Select Current
         * @description Point the console at ``payload.projectId`` and report what it now serves.
         *
         *     Answers the SAME :class:`CurrentSelectionResponse` as ``GET /projects/current``, and
         *     builds it from the SAME :func:`_resolve_current` — called after the switch, so it
         *     describes the new selection. One shape for "what is selected" whether you asked or
         *     changed it, which is what lets the SPA feed a switch's response straight into the
         *     header it would otherwise refetch.
         *
         *     **A degraded condition is NOT a precondition for selecting.** No servability probe
         *     runs before the switch: selecting a project whose directory has been deleted must
         *     SUCCEED, because that is precisely the state an operator selects into in order to
         *     then remove the row. The consequence is reported rather than refused — the response
         *     (and every subsequent read) names ``selected_project_missing`` /
         *     ``selected_project_unreadable`` — instead of the switch failing opaquely and leaving
         *     the operator pointed at a project they were trying to leave.
         *
         *     Two refusals, both ``404 project_not_registered``:
         *
         *     * an id no registry row answers to, raised by the registry underneath
         *       :meth:`~factory_console.services.project_selection.SelectionState._resolve_and_persist`
         *       — the one write the port makes fail loudly rather than succeed at pointing the
         *       console at nothing.
         *     * the reserved ``session`` id when NO root is pinned. Persistence never writes that
         *       id, so it would otherwise be accepted and move the session to a sentinel that
         *       names no directory — the same "succeeded at selecting nothing" outcome, reached by
         *       the one path the registry cannot see. From the caller's side the two are the same
         *       statement (this id names nothing this console can serve), so they get the same
         *       code rather than a second one the SPA would have to learn. With a pin present the
         *       sentinel is a perfectly ordinary target, and is the ONLY selectable target in
         *       pinned mode — which is why it does not require a registry at all.
         *
         *     **The switch is split across the offload, not run whole on the loop.** Only the
         *     on-change hook needs the event-loop thread — it rebuilds the file watcher for the new
         *     root, and a ``RealFileWatcher`` captures the running loop when it starts, so off the
         *     loop every switch would silently degrade to watcher-less. The registry round trip the
         *     switch also makes (persisting the selection and resolving its root) is a blocking
         *     ``sqlite3`` call like any other and has no such requirement, so it is offloaded
         *     through :func:`~factory_console.api.deps._read_registry` — which still names a store
         *     failure the ``registry_unreadable`` 503 — via
         *     :meth:`~factory_console.services.project_selection.SelectionState._resolve_and_persist`.
         *     Only :meth:`~factory_console.services.project_selection.SelectionState._apply_selected`
         *     (no I/O: it moves the in-memory selection and fires the hook) then runs on this
         *     thread, which is still the loop. The hook itself still returns immediately (the swap
         *     is deferred to a task), so nothing here blocks past the registry round trip already
         *     being awaited off the loop. The resolution that follows is the ordinary single
         *     offloaded hop.
         */
        readonly put: operations["select_current_api_v1_projects_current_put"];
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/projects/{project_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post?: never;
        /**
         * Remove Project
         * @description Stop tracking ``project_id``. ``204``, and nothing on the project's disk changes.
         *
         *     Removal is a CONSOLE-state operation: it deletes one row from the console's own
         *     table and never touches the project directory, which is why an empty ``204`` is the
         *     whole answer — there is no diff to preview and no artefact to report, unlike the
         *     ticket writes.
         *
         *     Three answers other than success, each named:
         *
         *     * the reserved ``session`` id → :class:`SessionProjectNotRemovable` (409). It is
         *       published as a row but was never registered, so there is nothing to delete.
         *     * an id no row answers to → :class:`ProjectNotRegistered` (404), decided in
         *       :func:`_remove_registered_project` from the port's ``False``.
         *     * an id that is neither 32 hex digits nor the sentinel → ``422`` at the boundary,
         *       from :data:`ProjectIdPath`, so a malformed id never reaches the store.
         *
         *     **Removing the selected project clears the selection twice over, and both are
         *     needed.** The schema's ``ON DELETE SET NULL`` clears the PERSISTED selection as part
         *     of the delete; this handler additionally clears the PROCESS-LOCAL one, which is what
         *     fires the on-change hook so the watcher supervisor releases the watcher rooted at the
         *     directory that is no longer tracked. Without it the in-memory selection would outlive
         *     its row and every project-scoped read would answer
         *     ``selected_project_not_registered`` instead of the ``no_project_selected`` that is
         *     actually true.
         *
         *     That clear is conditional — only when the removed row WAS the selection — because it
         *     is not free: it bumps the watcher generation and tears down live updates for every
         *     SSE client, which removing some unrelated row must not do.
         *
         *     **Only the hook stays on the loop; the registry round trip it needs is offloaded.**
         *     ``selection.select(None)`` used to run here whole, on the event-loop thread, because
         *     its on-change hook rebuilds the file watcher and a ``RealFileWatcher`` captures the
         *     running loop when it starts — off the loop every switch would silently degrade to
         *     watcher-less. But the ``sqlite3`` write that clear performs is a blocking call like
         *     any other registry access, and running it inline could stall the whole event loop —
         *     every other open SSE stream included — for as long as the store is contended. So the
         *     two halves are now split:
         *     :meth:`~factory_console.services.project_selection.SelectionState._resolve_and_persist`
         *     (the blocking clear) runs through :func:`~factory_console.api.deps._read_registry`
         *     like the removal above it, and only
         *     :meth:`~factory_console.services.project_selection.SelectionState._apply_selected`
         *     (which does no I/O — it fires the hook, on this thread, which is still the loop) runs
         *     inline. The hook itself still returns immediately (the watcher swap is deferred to a
         *     task), so nothing here blocks past the one small ``UPDATE``.
         */
        readonly delete: operations["remove_project_api_v1_projects__project_id__delete"];
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AddProjectRequest
         * @description The body of ``POST /projects``: which directory to start tracking, and its label.
         *
         *     ``extra="forbid"`` because this is the request that makes the console open an
         *     arbitrary path: a key the server does not understand is far more likely to be a
         *     caller sending a field this contract never agreed to than a harmless typo, and
         *     silently dropping it would let a client believe an option took effect.
         */
        readonly AddProjectRequest: {
            /** Path */
            readonly path: string;
            /** Name */
            readonly name?: string | null;
        };
        /**
         * CurrentSelectionResponse
         * @description What the console is serving right now — or the named reason it is serving nothing.
         *
         *     Exactly one of ``selected`` and ``reason`` is set, the same one-of discipline
         *     :class:`~factory_console.api.v1.runs.ProjectedArtifactRead` keeps between its
         *     ``data`` and ``reason``. The invariant is not restated as a validator because
         *     :func:`_current_response` is this model's ONLY constructor — called by both
         *     :func:`get_current` and :func:`select_current`, which is why it belongs there and
         *     not in either route — from a two-branch union; a second copy of the rule would have
         *     one owner and two homes.
         *
         *     ``reason`` is T111's :data:`SelectionFailure`, imported verbatim so ``/health``'s
         *     ``selectionReason``, the read endpoints' 409 codes and this field cannot come to
         *     disagree about spelling.
         */
        readonly CurrentSelectionResponse: {
            readonly selected?: components["schemas"]["RegisteredProjectOut"] | null;
            /** Reason */
            readonly reason?: ("no_selection" | "selected_project_not_registered" | "selected_project_missing" | "selected_project_unreadable") | null;
        };
        /**
         * DepNeighborhood
         * @description A ticket with its direct dependency edges and any unresolved dep ids.
         *
         *     ``unresolvedDeps`` holds ids listed in the ticket's ``dependsOn`` that have
         *     no matching ticket in the manifest.
         */
        readonly DepNeighborhood: {
            readonly ticket: components["schemas"]["TicketSummary"];
            /** Directdeps */
            readonly directDeps?: readonly components["schemas"]["TicketSummary"][];
            /** Directdependents */
            readonly directDependents?: readonly components["schemas"]["TicketSummary"][];
            /** Unresolveddeps */
            readonly unresolvedDeps?: readonly string[];
        };
        /**
         * DiffPreview
         * @description The set of per-file diffs a write produces, keyed by ticket id.
         */
        readonly DiffPreview: {
            /** Ticketid */
            readonly ticketId: string;
            /** Files */
            readonly files?: readonly components["schemas"]["FileDiff"][];
        };
        /**
         * FileDiff
         * @description A single file's planned or applied change, as a unified diff.
         *
         *     ``path`` is project-relative POSIX; ``changeKind`` classifies the change;
         *     ``diff`` is the unified-diff text the SPA renders.
         */
        readonly FileDiff: {
            /** Path */
            readonly path: string;
            /**
             * Changekind
             * @enum {string}
             */
            readonly changeKind: "create" | "modify" | "delete";
            /** Diff */
            readonly diff: string;
        };
        /**
         * GraphEdge
         * @description A directed dependency edge: ``source`` depends on ``target``.
         *
         *     Only edges whose ``target`` resolves to a known node are emitted (dangling
         *     ``dependsOn`` ids are intentionally NOT edges, consistent with
         *     :attr:`~factory_console.domain.deps.DepNeighborhood.unresolvedDeps`); self-loops
         *     are dropped. Frozen and ``extra='forbid'`` like the other domain models.
         */
        readonly GraphEdge: {
            /** Source */
            readonly source: string;
            /** Target */
            readonly target: string;
        };
        /**
         * GraphNode
         * @description One ticket as a graph node, coloured by its resolved run-state.
         *
         *     Carries the same identity/classification fields as the list-view summary —
         *     ``id``, ``title``, ``status``, ``track``, ``milestone`` — plus the
         *     ``runState`` the shared projection already resolved, so a node's colour
         *     matches the list and deps views. Frozen and ``extra='forbid'`` like the other
         *     domain models.
         */
        readonly GraphNode: {
            /** Id */
            readonly id: string;
            /** Title */
            readonly title: string;
            /** Status */
            readonly status: string;
            /** Track */
            readonly track?: string | null;
            /** Milestone */
            readonly milestone?: string | null;
            readonly runState: components["schemas"]["RunState"];
        };
        /** HTTPValidationError */
        readonly HTTPValidationError: {
            /** Detail */
            readonly detail?: readonly components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Liveness probe body: ``ok``, ``version``, and what the console is looking at.
         *
         *     The last three fields are one answer in three parts, and each combination is a
         *     distinct, named state rather than an accident of nulls:
         *
         *     * selection resolved → ``projectRoot`` set, ``selectedProjectId`` set,
         *       ``selectionReason`` ``None``.
         *     * nothing selected → all of ``projectRoot`` and ``selectedProjectId`` ``None``,
         *       ``selectionReason`` ``"no_selection"``.
         *     * selected but unusable → ``selectedProjectId`` set and ``selectionReason`` naming
         *       which failure; ``projectRoot`` is the unusable PATH when one is known (the row
         *       exists, the directory does not), and ``None`` when it is not (the id names no
         *       row at all).
         *     * the registry could not be read → every one of the three is ``None``. See
         *       :func:`_resolve_selection` for why that is not a ``selectionReason``.
         *
         *     ``ok`` is ``True`` in all four: it reports the PROCESS, and none of these is a
         *     process fault.
         */
        readonly HealthResponse: {
            /** Ok */
            readonly ok: boolean;
            /** Version */
            readonly version: string;
            /** Projectroot */
            readonly projectRoot: string | null;
            /** Selectedprojectid */
            readonly selectedProjectId: string | null;
            /** Selectionreason */
            readonly selectionReason: ("no_selection" | "selected_project_not_registered" | "selected_project_missing" | "selected_project_unreadable") | null;
        };
        /**
         * LevelSpend
         * @description One agent level's share of the bill — how much of it was review, not build.
         *
         *     ``level`` is the ledger's ``level`` field as written (``ticket``, and whatever
         *     else the factory names): the vocabulary belongs to the factory, so no closed
         *     set is enumerated here and an unrecognised level appears rather than vanishing.
         */
        readonly LevelSpend: {
            /** Level */
            readonly level: string;
            /**
             * Costusd
             * @default 0
             */
            readonly costUsd: number;
            /**
             * Entries
             * @default 0
             */
            readonly entries: number;
        };
        /**
         * ModelSpend
         * @description One model's project-wide share of the bill.
         *
         *     ``model`` is the factory's model id VERBATIM (e.g. ``claude-opus-4-8[1m]``).
         *     Nothing here maps it to a display name: mapping is the view's job, and a
         *     mapping applied at this layer would silently hide a model the console has not
         *     heard of behind whatever its fallback happened to be.
         *
         *     Distinct from the ledger's same-named
         *     :class:`~factory_console.domain.ledger.ModelSpend`, which is the RAW shape of
         *     one ``by_model`` value on one entry. This is the aggregate across every entry.
         *
         *     ``tokens.total`` is the SUM of one total per contributing entry, and each of
         *     those is arrived at differently: an entry with a ``by_model`` breakdown carries
         *     no total there, so its contribution is derived (the four counts summed), while
         *     an entry with no breakdown contributes the entry's own written ``total``. A
         *     model fed by both kinds therefore reports a total that need NOT equal this
         *     row's other four fields summed — the factory's written total is its own
         *     measurement, not a restatement of the parts, and this row keeps it rather than
         *     quietly replacing it with a figure the ledger never recorded.
         */
        readonly ModelSpend: {
            /** Model */
            readonly model: string;
            /**
             * Costusd
             * @default 0
             */
            readonly costUsd: number;
            /**
             * @default {
             *       "input": 0,
             *       "output": 0,
             *       "cacheRead": 0,
             *       "cacheCreation": 0,
             *       "total": 0
             *     }
             */
            readonly tokens: components["schemas"]["SpendTokens"];
        };
        /**
         * Project
         * @description Resolved paths for one App Factory project, discovered per request.
         *
         *     ``roadmapPath``, ``runStateDir`` and ``runStateSource`` are ``None`` when the
         *     corresponding file or directory is absent from the target project (all are
         *     optional in the project layout).
         *
         *     ``runStateSource`` is the resolved run-state artifact — the factory's
         *     ``.factory/run-state.json`` OR a legacy marker directory — and is what
         *     run-state reads dispatch on. ``runStateDir`` keeps its original meaning
         *     exactly: a path ONLY when the resolved source is a directory, so a
         *     JSON-sourced project has ``runStateDir is None``. Read run-state through
         *     ``runStateSource``; ``runStateDir`` answers only "which directory, if any, is
         *     off-limits to the writer".
         */
        readonly Project: {
            /**
             * Rootpath
             * Format: path
             */
            readonly rootPath: string;
            /**
             * Ticketsmanifestpath
             * Format: path
             */
            readonly ticketsManifestPath: string;
            /**
             * Ticketsdir
             * Format: path
             */
            readonly ticketsDir: string;
            /** Roadmappath */
            readonly roadmapPath?: string | null;
            /** Runstatedir */
            readonly runStateDir?: string | null;
            readonly runStateSource?: components["schemas"]["RunStateSource"] | null;
            /**
             * Discoveredat
             * Format: date-time
             */
            readonly discoveredAt: string;
        };
        /**
         * ProjectListResponse
         * @description Envelope for the projects list: the switcher rows and their count.
         *
         *     The ``{items, total}`` shape ``/tickets``, ``/search`` and ``/runs`` already use, so
         *     a client that unwraps ``items`` for three lists does not special-case a fourth.
         *     ``total`` is ``len(items)`` — there is no filtering and no pagination, and the count
         *     INCLUDES the session row when one is present, because that row is a row of the
         *     dropdown like any other.
         */
        readonly ProjectListResponse: {
            /** Items */
            readonly items: readonly components["schemas"]["RegisteredProjectOut"][];
            /** Total */
            readonly total: number;
        };
        /**
         * ProjectedArtifactRead
         * @description One artifact read as it is DISCLOSED: the declared fields only, or the reason.
         *
         *     The wire twin of :class:`~factory_console.domain.runs.ArtifactRead`, and
         *     deliberately not that class. The domain type carries ``dict[str, Any]`` because the
         *     reading layer models no field inside a factory-written file; this one carries
         *     ``dict[str, str]`` holding at most :data:`DISCLOSED_ARTIFACT_FIELDS`, because
         *     "unmodelled" is a reason to publish LESS, not everything. See the module docstring
         *     for why the narrowing lives at this boundary and not below it.
         *
         *     ``path`` and ``reason`` cross unchanged: both are the console's own vocabulary — a
         *     path it computed and a reason it named — not content copied out of another
         *     program's file, so neither is a disclosure this rule is about, and both are what
         *     an operator acts on.
         *
         *     :class:`ArtifactRead`'s invariant survives the projection: exactly one of ``data``
         *     and ``reason`` is set. A successful read whose payload declares none of the fields
         *     projects to ``data={}`` — an empty object, which is NOT ``None`` — so "read, and it
         *     named nothing this console recognises" stays distinct from "not read", exactly as
         *     it is one layer down. The invariant is not re-asserted with a validator here: this
         *     module is its only constructor and :meth:`from_artifact` is its only route, so a
         *     second copy of the rule would have one owner and two homes.
         */
        readonly ProjectedArtifactRead: {
            /**
             * Path
             * Format: path
             */
            readonly path: string;
            /** Data */
            readonly data?: {
                readonly [key: string]: string;
            } | null;
            /** Reason */
            readonly reason?: ("absent" | "unreadable" | "unparseable" | "too_large") | null;
        };
        /**
         * ProjectedRunRecord
         * @description One manifest ticket's two artifacts, as disclosed — the wire twin of ``RunRecord``.
         *
         *     Field for field :class:`~factory_console.domain.run_record.RunRecord`, with each
         *     :class:`ArtifactRead` replaced by its :class:`ProjectedArtifactRead`. The record's
         *     own rule is untouched and is the reason this type is a twin rather than a summary:
         *     both sources are still carried SEPARATELY, each with its own ``reason``, so no
         *     absence is flattened into a boolean or inferred from its neighbour.
         */
        readonly ProjectedRunRecord: {
            /** Ticketid */
            readonly ticketId: string;
            readonly result: components["schemas"]["ProjectedArtifactRead"];
            readonly receipt: components["schemas"]["ProjectedArtifactRead"];
        };
        /**
         * RegisteredProjectOut
         * @description One row of the project switcher: a tracked project, its condition, its state.
         *
         *     The DISCLOSURE BOUNDARY for a registry row, and the wire twin of
         *     :class:`~factory_console.domain.registry.RegistryEntry` — exactly as
         *     :class:`~factory_console.api.v1.runs.ProjectedArtifactRead` is for an artefact. The
         *     two constructors below name every field EXPLICITLY and never ``model_dump()`` the
         *     store entity, so a column the store track adds later (a last-opened timestamp, a
         *     cached branch name, an operator note) cannot reach the browser by accident. That
         *     matters more here than for most models: unlike a factory artefact, these rows are
         *     the console's OWN writable table, which is the kind of thing that grows columns.
         *
         *     ``selected`` and ``registered`` are flattened onto the row rather than left for the
         *     client to derive. Both are answers only the server holds — the first needs the
         *     session's selection state, the second is the ``session`` sentinel's defining
         *     property — and a dropdown that had to compute either would re-derive server state
         *     from an id string.
         */
        readonly RegisteredProjectOut: {
            /** Id */
            readonly id: string;
            /** Name */
            readonly name: string;
            /**
             * Path
             * Format: path
             */
            readonly path: string;
            /** Addedat */
            readonly addedAt: string | null;
            /** Registered */
            readonly registered: boolean;
            /** Selected */
            readonly selected: boolean;
            /**
             * Condition
             * @enum {string}
             */
            readonly condition: "unreadable" | "path_missing" | "not_a_project" | "no_factory_dir" | "ok";
        };
        /**
         * Roadmap
         * @description The project roadmap document (``ROADMAP.md``).
         *
         *     ``milestones`` is the structured breakdown parsed from the body — empty for a
         *     body with no ``## `` headings — leaving ``bodyMarkdown``/``bodyHtml`` as the
         *     full document for verbatim rendering.
         */
        readonly Roadmap: {
            /**
             * Path
             * Format: path
             */
            readonly path: string;
            /** Bodymarkdown */
            readonly bodyMarkdown: string;
            /** Bodyhtml */
            readonly bodyHtml: string;
            /** Milestones */
            readonly milestones?: readonly components["schemas"]["RoadmapMilestone"][];
        };
        /**
         * RoadmapAbsent
         * @description Response when the project has no roadmap: ``present: false``.
         *
         *     The backend-owned discriminator: :class:`~factory_console.domain.deps.Roadmap`
         *     carries no ``present`` field, so the frontend discriminates the present branch
         *     from this absent one on that key's presence.
         */
        readonly RoadmapAbsent: {
            /**
             * Present
             * @default false
             * @constant
             */
            readonly present: false;
        };
        /**
         * RoadmapItem
         * @description A single milestone list-item parsed from ``ROADMAP.md``.
         *
         *     ``text`` is the cleaned item label (marker and checkbox stripped); ``done``
         *     reflects the checkbox state (``True``/``False`` for ``[x]``/``[ ]``, ``None``
         *     when the item carries no checkbox); ``ticketId`` is the item's linked ticket
         *     id when one is present, else ``None``.
         */
        readonly RoadmapItem: {
            /** Text */
            readonly text: string;
            /** Ticketid */
            readonly ticketId?: string | null;
            /** Done */
            readonly done?: boolean | null;
        };
        /**
         * RoadmapMilestone
         * @description A ``## `` heading from ``ROADMAP.md`` with its list of items.
         */
        readonly RoadmapMilestone: {
            /** Name */
            readonly name: string;
            /** Items */
            readonly items?: readonly components["schemas"]["RoadmapItem"][];
        };
        /**
         * RunListResponse
         * @description Envelope for the runs list: one record per manifest ticket, and their count.
         *
         *     ``items`` are :class:`ProjectedRunRecord`, not the service's own
         *     :class:`RunRecord` — see the module docstring: the composed record is the domain's
         *     answer, and this envelope is what may be disclosed of it.
         */
        readonly RunListResponse: {
            /** Items */
            readonly items: readonly components["schemas"]["ProjectedRunRecord"][];
            /** Total */
            readonly total: number;
        };
        /**
         * RunState
         * @description A ticket's run-state, derived from the project's resolved run-state source.
         *
         *     Subclasses ``str`` so a member compares and serializes as its string value
         *     (``RunState.todo == "todo"``); the value is the name its source uses.
         * @enum {string}
         */
        readonly RunState: "todo" | "in-flight" | "ready" | "merged" | "in_progress" | "in_part" | "in_submilestone" | "flagged" | "failed" | "needs_human" | "unknown" | "absent" | "unreadable";
        /**
         * RunStateSource
         * @description A resolved run-state artifact: its form (``kind``) and where it lives.
         *
         *     Frozen and ``extra="forbid"`` like every other domain model, and carried on
         *     :class:`~factory_console.domain.project.Project` so the whole request reads
         *     through ONE resolution rather than each call site re-probing the filesystem.
         */
        readonly RunStateSource: {
            /**
             * Kind
             * @enum {string}
             */
            readonly kind: "json" | "directory";
            /**
             * Path
             * Format: path
             */
            readonly path: string;
        };
        /**
         * SearchHit
         * @description One ranked full-text search result: a ticket summary, its score, and hits.
         *
         *     ``score`` is the summed per-field weight the ranking accrued for this ticket
         *     (higher is more relevant); ``matchedFields`` names the fields any query token
         *     hit, in a stable field order (``id``, ``title``, ``provides``,
         *     ``bodyMarkdown``). Frozen and ``extra='forbid'`` like the other domain models.
         *
         *     The ``ScoredTicket`` → ``SearchHit`` re-key both adapters share lives in
         *     ``file_adapter/search.py``'s ``to_search_hits`` — next to its ``ScoredTicket``
         *     input, importing this model downward (the allowed ``file_adapter → domain``
         *     direction) — so ``domain`` never has to depend on a ``file_adapter`` type.
         */
        readonly SearchHit: {
            readonly ticket: components["schemas"]["TicketSummary"];
            /** Score */
            readonly score: number;
            /** Matchedfields */
            readonly matchedFields?: readonly string[];
        };
        /**
         * SearchResponse
         * @description Envelope for the search results: the ranked hits and their count.
         */
        readonly SearchResponse: {
            /** Items */
            readonly items: readonly components["schemas"]["SearchHit"][];
            /** Total */
            readonly total: number;
        };
        /**
         * SelectProjectRequest
         * @description The body of ``PUT /projects/current``: which row the console should serve next.
         *
         *     A body rather than a path parameter because the resource being replaced is
         *     ``/projects/current`` — "what is selected" — and the id is its new VALUE, not its
         *     address. ``extra="forbid"`` for the same reason as :class:`AddProjectRequest`.
         */
        readonly SelectProjectRequest: {
            /** Projectid */
            readonly projectId: string;
        };
        /**
         * SkippedLineInfo
         * @description A ledger line that did not parse, over HTTP: which line, and why.
         *
         *     T79's :class:`~factory_console.domain.ledger.SkippedLine` also carries an
         *     ``excerpt`` of the offending line; it is NOT projected here. The excerpt exists
         *     for a human reading the file, and the ledger is a file the console only
         *     observes — putting a slice of its raw bytes on the wire would widen what this
         *     read-only endpoint can disclose for no view that needs it.
         *
         *     ``lineNo`` is ``0`` when the failure belongs to the whole file rather than to
         *     any one line (unreadable, or over the reader's size cap).
         */
        readonly SkippedLineInfo: {
            /** Lineno */
            readonly lineNo: number;
            /**
             * Reason
             * @enum {string}
             */
            readonly reason: "not_json" | "invalid_entry" | "partial_line" | "file_too_large" | "unreadable";
        };
        /**
         * SourceInfo
         * @description Whether this project HAS a ledger, whether it could be READ, and where it is.
         *
         *     THE field that keeps "no ledger" from being read as "$0.00". ``found: false``
         *     is the fresh-clone case and a client must be able to act on it directly, rather
         *     than inferring absence from a zero total — which an empty ledger also produces,
         *     and which for an unmeasured project would be a false statement about real money.
         *
         *     ``read`` carries the SAME distinction one step further, because ``found`` alone
         *     does not survive a ledger that exists and could not be opened. A file over the
         *     reader's size cap, or one that cannot be stat'd or read at all, yields zero
         *     entries — so ``found: true`` over zeroed totals would state that a ledger WAS
         *     read and measured nothing, which for an 11 MiB file full of real lanes is the
         *     same false statement ``found`` exists to prevent, merely relocated. ``read:
         *     false`` says the bill is UNKNOWN rather than zero; the reason is in
         *     :attr:`SpendResponse.skipped`, at ``lineNo`` 0.
         *
         *     So ``read`` means "the figures below came from actually reading a file", and it
         *     defaults to ``False`` — the honest value for the no-ledger case, where there was
         *     nothing to read. ``totals`` is a MEASURED zero only when ``read`` is true; on
         *     ``found: true, read: false`` it is a placeholder for a bill nobody could count.
         *
         *     ``path`` is where the console LOOKED, not proof that anything was there — it
         *     is populated on all three outcomes, including ``found: false``. A view whose
         *     entire job in the no-ledger case is to explain the absence has to be able to
         *     name the place, and reading that off ``found`` instead would make the
         *     frontend restate the ledger's location in its own source. ``found`` and
         *     ``read``, not this field, are what say whether the file exists and was
         *     parsed. It is ``None`` only when the path could not be formed at all.
         */
        readonly SourceInfo: {
            /** Found */
            readonly found: boolean;
            /**
             * Read
             * @default false
             */
            readonly read: boolean;
            /** Path */
            readonly path?: string | null;
        };
        /**
         * SpendResponse
         * @description The ``GET /api/v1/spend`` body: a :class:`SpendReport` plus how it was read.
         *
         *     Extends the pure report with the two facts only the caller holds — whether the
         *     ledger existed at all (:class:`SourceInfo`) and which of its lines could not be
         *     read — by SUBCLASSING it, so the wire shape cannot drift from the aggregate as
         *     fields are added to one and not the other.
         *
         *     ``skippedOmitted`` counts lines that failed beyond the reader's detail cap. It
         *     is not decoration: T79 caps how many skipped lines it materialises but keeps
         *     counting them, and dropping that count here would make a catastrophically
         *     corrupt ledger report exactly as partial as a mildly corrupt one.
         *
         *     ``len(skipped) + skippedOmitted`` is the exact number of lines missing from
         *     :attr:`SpendReport.totals` — **for per-line failures only**. A skip at
         *     ``lineNo`` 0 is not a line: it reports that the WHOLE file was not read
         *     (``unreadable``, or over the reader's size cap), so it stands for an unknown
         *     number of lines, not for one. That case is exactly ``source.read: false``, and a
         *     client counting unparsed lines must branch on it rather than render "1 line
         *     could not be read" over a ledger nothing ever opened.
         */
        readonly SpendResponse: {
            /**
             * Attribution
             * @default full-to-each-id
             * @constant
             */
            readonly attribution: "full-to-each-id";
            /**
             * @default {
             *       "costUsd": 0,
             *       "entries": 0,
             *       "tokens": {
             *         "cacheCreation": 0,
             *         "cacheRead": 0,
             *         "input": 0,
             *         "output": 0,
             *         "total": 0
             *       }
             *     }
             */
            readonly totals: components["schemas"]["SpendTotals"];
            /** Byticket */
            readonly byTicket?: readonly components["schemas"]["TicketSpend"][];
            /** Bymodel */
            readonly byModel?: readonly components["schemas"]["ModelSpend"][];
            /** Bylevel */
            readonly byLevel?: readonly components["schemas"]["LevelSpend"][];
            readonly source: components["schemas"]["SourceInfo"];
            /** Skipped */
            readonly skipped?: readonly components["schemas"]["SkippedLineInfo"][];
            /**
             * Skippedomitted
             * @default 0
             */
            readonly skippedOmitted: number;
        };
        /**
         * SpendTokens
         * @description Summed token counts in the console's OWN camelCase wire vocabulary.
         *
         *     A near-twin of :class:`~factory_console.domain.ledger.TokenCounts`, and
         *     deliberately NOT that class. The ledger's model is shaped by the FILE: it
         *     spells the factory's ``cache_read``/``cache_creation`` and it is
         *     ``extra="ignore"`` because another program owns that format. Both traits are
         *     wrong for a response — the REST v1 contract is camelCase, and a shape this repo
         *     builds AND serialises end to end takes the house ``extra="forbid"``.
         *
         *     Reusing the ledger model here would publish snake_case keys in the one nested
         *     object of an otherwise camelCase body, and would leave the console's published
         *     contract to be rewritten by a future edit to a model that exists to track
         *     someone else's file. So the parse shape and the wire shape are separate types,
         *     converted in exactly one place —
         *     :meth:`~factory_console.domain.spend_calc._Tokens.frozen`.
         */
        readonly SpendTokens: {
            /**
             * Input
             * @default 0
             */
            readonly input: number;
            /**
             * Output
             * @default 0
             */
            readonly output: number;
            /**
             * Cacheread
             * @default 0
             */
            readonly cacheRead: number;
            /**
             * Cachecreation
             * @default 0
             */
            readonly cacheCreation: number;
            /**
             * Total
             * @default 0
             */
            readonly total: number;
        };
        /**
         * SpendTotals
         * @description What the whole read cost: dollars, entry count, and summed token counts.
         *
         *     ``entries`` counts the ledger entries that PARSED. It is deliberately reported
         *     beside the money so a caller can compare it against
         *     :attr:`SpendResponse.skipped` and see that a total was computed over 40 of 43
         *     lines — a partial bill that says so, rather than a confident wrong number.
         *
         *     ``tokens`` sums the entries' own ``tokens`` objects field by field, including
         *     the factory's written ``total``; it is not recomputed from the parts, so it
         *     reports what the factory measured.
         */
        readonly SpendTotals: {
            /**
             * Costusd
             * @default 0
             */
            readonly costUsd: number;
            /**
             * Entries
             * @default 0
             */
            readonly entries: number;
            /**
             * @default {
             *       "input": 0,
             *       "output": 0,
             *       "cacheRead": 0,
             *       "cacheCreation": 0,
             *       "total": 0
             *     }
             */
            readonly tokens: components["schemas"]["SpendTokens"];
        };
        /**
         * Ticket
         * @description A manifest entry joined with the content file it points at.
         *
         *     ``raw`` preserves the unmodified manifest entry — including fields this model
         *     does not name — for forward-compatibility with future factory versions.
         *     ``extra='forbid'`` governs the model's *own* fields; it does not restrict the
         *     contents of the ``raw`` mapping. ``runState`` defaults to
         *     :attr:`RunState.unknown` and is resolved per request by the service on the
         *     detail path (the manifest/enrichment build sites leave it at the default).
         *
         *     **``content`` and ``bodyMarkdown`` are the same ticket, and neither replaces the
         *     other.** ``bodyMarkdown`` is the RENDERED view — what the detail page displays and
         *     what full-text search indexes — and it exists for both storage formats, which is
         *     the whole reason a reader can change format without a consumer noticing.
         *     ``content`` is the structured SOURCE, and it is what an edit form seeds from: you
         *     cannot offer to edit five fields you were only ever handed a paragraph of.
         *
         *     ``content`` is therefore ``None`` for a Markdown ticket, and that ``None`` is
         *     load-bearing rather than a gap. It is the read-side twin of
         *     :class:`~factory_console.file_adapter.ticket_content.TicketFormatRetired`: a
         *     ticket with no structured content is exactly a ticket whose edit the write path
         *     refuses with a 409, so a client that checks it declines to open the form instead
         *     of presenting five blank boxes whose Save is guaranteed to fail.
         *
         *     ``files`` stays beside it and is not redundant with ``content.criticalFiles``.
         *     ``files`` is the format-agnostic DISPLAY projection — a v2 ticket has one from its
         *     manifest entry and no ``content`` at all — while ``criticalFiles`` is the editable
         *     field of the content file. They agree for a v3 ticket by construction (see
         *     :func:`~factory_console.file_adapter.ticket_content.enrich_ticket`), and the day
         *     they would not is the day one of the two formats stopped answering.
         */
        readonly Ticket: {
            /** Id */
            readonly id: string;
            /** Title */
            readonly title: string;
            /** Status */
            readonly status: string;
            /** Track */
            readonly track?: string | null;
            /** Milestone */
            readonly milestone?: string | null;
            /** @default unknown */
            readonly runState: components["schemas"]["RunState"];
            /** Dependson */
            readonly dependsOn?: readonly string[];
            /** Provides */
            readonly provides?: readonly string[];
            /** Files */
            readonly files?: readonly string[];
            /**
             * Filepath
             * Format: path
             */
            readonly filePath: string;
            readonly content?: components["schemas"]["TicketContentFields"] | null;
            /** Bodymarkdown */
            readonly bodyMarkdown: string;
            /** Bodyhtml */
            readonly bodyHtml: string;
            /** Raw */
            readonly raw: {
                readonly [key: string]: unknown;
            };
        };
        /**
         * TicketContentFields
         * @description The five structured fields an App Factory v3 ticket's CONTENT file carries.
         *
         *     **One definition, both directions.** This is the read projection published on
         *     :attr:`Ticket.content` AND — by inheritance in
         *     :mod:`~factory_console.domain.write` — the write surface a client sends. They are
         *     the same five fields because they mirror the same ``schemas/ticket.schema.json``,
         *     and a console whose edit form could not send back exactly what it was shown would
         *     lose a field on every round-trip. It lives here, in the read module, because the
         *     dependency already runs this way: ``write`` imports ``ticket``, never the reverse.
         *
         *     **This replaced a single free-text ``bodyMarkdown`` plus an open ``frontMatter``
         *     dict, and the change is to what a user EDITS, not merely to how it is stored.**
         *     A v3 ticket is structured, and the schema sets ``additionalProperties: false`` —
         *     so there is nowhere left to put a paragraph that belongs to no field, and nowhere
         *     to stash an arbitrary extra key. A console that kept accepting them would be
         *     accepting input it could not write.
         *
         *     Constraints mirror that schema, and on the write path they are enforced HERE
         *     rather than only at render time so a malformed request is a 422 naming the field —
         *     the requester's error, answered at the boundary — instead of a 500 raised by the
         *     console's own validation of text it just built. ``criticalFiles`` and
         *     ``verificationCommands`` carry the schema's ``minItems: 1``, and the schema states
         *     the reasons: an empty ``critical_files`` silently weakens the overlap filter that
         *     keeps two lanes off one path, and under INV-42 a ticket declaring no verification
         *     command can never be verified, only assumed.
         */
        readonly TicketContentFields: {
            /** Context */
            readonly context: string;
            /** Approach */
            readonly approach: string;
            /** Criticalfiles */
            readonly criticalFiles: readonly string[];
            /** Interfacedata */
            readonly interfaceData: string;
            /** Verificationcommands */
            readonly verificationCommands: readonly string[];
            /** Verificationnotes */
            readonly verificationNotes?: string | null;
        };
        /**
         * TicketDraft
         * @description Inbound request body to CREATE a ticket.
         *
         *     ``id`` is validated against :data:`TICKET_ID_PATTERN` at this boundary; the rest
         *     split cleanly in two, matching where v3 stores them. ``title`` / ``track`` /
         *     ``milestone`` / ``dependsOn`` / ``provides`` are INDEX fields and land in
         *     ``tickets.json``; the inherited five are CONTENT fields and land in the ticket's
         *     own file. Nothing here is written to both, which is what keeps the two from
         *     disagreeing.
         *
         *     ``files`` is gone from this surface: v3's index carries no such key, and the
         *     content file's ``criticalFiles`` is the same information stored where the factory
         *     reads it from.
         */
        readonly TicketDraft: {
            /** Context */
            readonly context: string;
            /** Approach */
            readonly approach: string;
            /** Criticalfiles */
            readonly criticalFiles: readonly string[];
            /** Interfacedata */
            readonly interfaceData: string;
            /** Verificationcommands */
            readonly verificationCommands: readonly string[];
            /** Verificationnotes */
            readonly verificationNotes?: string | null;
            /** Id */
            readonly id: string;
            /** Title */
            readonly title: string;
            /** Track */
            readonly track?: string | null;
            /** Milestone */
            readonly milestone?: string | null;
            /** Dependson */
            readonly dependsOn?: readonly string[];
            /**
             * Provides
             * @default
             */
            readonly provides: string;
        };
        /**
         * TicketEdit
         * @description Inbound request body to EDIT a ticket.
         *
         *     Identical to :class:`TicketDraft` minus ``id`` — the id of the ticket being
         *     edited comes from the path parameter, not the body.
         */
        readonly TicketEdit: {
            /** Context */
            readonly context: string;
            /** Approach */
            readonly approach: string;
            /** Criticalfiles */
            readonly criticalFiles: readonly string[];
            /** Interfacedata */
            readonly interfaceData: string;
            /** Verificationcommands */
            readonly verificationCommands: readonly string[];
            /** Verificationnotes */
            readonly verificationNotes?: string | null;
            /** Title */
            readonly title: string;
            /** Track */
            readonly track?: string | null;
            /** Milestone */
            readonly milestone?: string | null;
            /** Dependson */
            readonly dependsOn?: readonly string[];
            /**
             * Provides
             * @default
             */
            readonly provides: string;
        };
        /**
         * TicketGraph
         * @description The whole-project dependency DAG: run-state-coloured nodes and edges.
         *
         *     ``nodes`` are the ticket summaries in list order; ``edges`` are the resolved,
         *     self-loop-free, de-duplicated ``dependsOn`` relations. The frontend maps this
         *     payload to Cytoscape element format (not this model's concern). Frozen and
         *     ``extra='forbid'`` like the other domain models.
         */
        readonly TicketGraph: {
            /** Nodes */
            readonly nodes?: readonly components["schemas"]["GraphNode"][];
            /** Edges */
            readonly edges?: readonly components["schemas"]["GraphEdge"][];
        };
        /**
         * TicketListResponse
         * @description Envelope for the tickets list: the matching summaries and their count.
         */
        readonly TicketListResponse: {
            /** Items */
            readonly items: readonly components["schemas"]["TicketSummary"][];
            /** Total */
            readonly total: number;
        };
        /**
         * TicketSpend
         * @description One ticket id's attributed spend, under :data:`ATTRIBUTION_RULE`.
         *
         *     ``attributedCostUsd`` is named for the rule: it is the sum of the FULL cost of
         *     every entry naming this ticket, so summing this field across tickets does not
         *     give :attr:`SpendTotals.costUsd` and is not meant to.
         *
         *     ``models`` lists the model ids seen on this ticket's entries, sorted, as the
         *     factory wrote them — a set for the view to render, not a per-model breakdown
         *     (that is :class:`ModelSpend`, which is project-wide).
         */
        readonly TicketSpend: {
            /** Ticketid */
            readonly ticketId: string;
            /**
             * Attributedcostusd
             * @default 0
             */
            readonly attributedCostUsd: number;
            /**
             * Entries
             * @default 0
             */
            readonly entries: number;
            /** Models */
            readonly models?: readonly string[];
        };
        /**
         * TicketSummary
         * @description List-projection of a ticket for the tickets index view.
         *
         *     ``runState`` is resolved per request by probing the factory run-state
         *     directory; ``depCount`` / ``dependentCount`` come from reverse-indexing
         *     ``dependsOn`` across the manifest.
         */
        readonly TicketSummary: {
            /** Id */
            readonly id: string;
            /** Title */
            readonly title: string;
            /** Status */
            readonly status: string;
            /** Track */
            readonly track?: string | null;
            /** Milestone */
            readonly milestone?: string | null;
            readonly runState: components["schemas"]["RunState"];
            /** Depcount */
            readonly depCount: number;
            /** Dependentcount */
            readonly dependentCount: number;
        };
        /** ValidationError */
        readonly ValidationError: {
            /** Location */
            readonly loc: readonly (string | number)[];
            /** Message */
            readonly msg: string;
            /** Error Type */
            readonly type: string;
            /** Input */
            readonly input?: unknown;
            /** Context */
            readonly ctx?: Record<string, never>;
        };
        /**
         * WriteResult
         * @description Uniform envelope returned by every write endpoint (apply or dry-run).
         *
         *     Two shapes:
         *
         *     * **Apply** → ``applied=True``, ``ticket`` set to the re-read
         *       :class:`~factory_console.domain.ticket.Ticket`, ``changedFiles`` the paths
         *       actually written, ``diff`` the preview of what was written.
         *     * **Dry-run** → ``applied=False``, ``ticket=None``, ``changedFiles`` the
         *       planned paths, ``diff`` the preview of what would be written.
         */
        readonly WriteResult: {
            /** Applied */
            readonly applied: boolean;
            /** Ticketid */
            readonly ticketId: string;
            /** Changedfiles */
            readonly changedFiles?: readonly string[];
            readonly diff: components["schemas"]["DiffPreview"];
            readonly ticket?: components["schemas"]["Ticket"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly get_project_api_v1_project_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    readonly list_tickets_api_v1_tickets_get: {
        readonly parameters: {
            readonly query?: {
                readonly status?: string | null;
                readonly track?: string | null;
                readonly milestone?: string | null;
                readonly q?: string | null;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["TicketListResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly create_ticket_api_v1_tickets_post: {
        readonly parameters: {
            readonly query?: {
                readonly dryRun?: boolean;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["TicketDraft"];
            };
        };
        readonly responses: {
            /** @description Dry-run preview: the diff that WOULD be written; nothing was created. */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["WriteResult"];
                };
            };
            /** @description Successful Response */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["WriteResult"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_ticket_api_v1_tickets__ticket_id__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly ticket_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Ticket"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly edit_ticket_api_v1_tickets__ticket_id__put: {
        readonly parameters: {
            readonly query?: {
                readonly dryRun?: boolean;
            };
            readonly header?: never;
            readonly path: {
                readonly ticket_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["TicketEdit"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["WriteResult"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly delete_ticket_api_v1_tickets__ticket_id__delete: {
        readonly parameters: {
            readonly query?: {
                readonly dryRun?: boolean;
            };
            readonly header?: never;
            readonly path: {
                readonly ticket_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["WriteResult"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_ticket_deps_api_v1_tickets__ticket_id__deps_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly ticket_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["DepNeighborhood"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_health_api_v1_health_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readonly get_roadmap_api_v1_roadmap_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Roadmap"] | components["schemas"]["RoadmapAbsent"];
                };
            };
        };
    };
    readonly search_api_v1_search_get: {
        readonly parameters: {
            readonly query: {
                readonly q: string;
                readonly limit?: number;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_graph_api_v1_graph_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["TicketGraph"];
                };
            };
        };
    };
    readonly events_api_v1_events_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": unknown;
                };
            };
        };
    };
    readonly get_spend_api_v1_spend_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SpendResponse"];
                };
            };
        };
    };
    readonly list_runs_api_v1_runs_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["RunListResponse"];
                };
            };
        };
    };
    readonly list_projects_api_v1_projects_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ProjectListResponse"];
                };
            };
        };
    };
    readonly add_project_api_v1_projects_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["AddProjectRequest"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["RegisteredProjectOut"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_current_api_v1_projects_current_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["CurrentSelectionResponse"];
                };
            };
        };
    };
    readonly select_current_api_v1_projects_current_put: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["SelectProjectRequest"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["CurrentSelectionResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly remove_project_api_v1_projects__project_id__delete: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly project_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
