/**
 * DO NOT EDIT — regenerate with pnpm codegen
 *
 * Generated by openapi-typescript from the server's /api/v1/openapi.json.
 * Any manual edit is overwritten the next time `pnpm codegen` runs.
 */

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/api/v1/project": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Project
         * @description Return the discovered target :class:`Project` for the running console.
         *
         *     Reads the discovered root from ``request.app.state.project_root`` — a ``Path``
         *     ``create_app`` requires at boot — and returns ``adapter.load_project(root)``.
         *     Raises nothing itself: a ``ProjectNotFound`` from the adapter propagates to the
         *     registered domain-error handler, which maps it to the 404 envelope.
         */
        readonly get: operations["get_project_api_v1_project_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/tickets": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * List Tickets
         * @description Return the ticket summaries matching the ``status``/``track``/``milestone``/``q`` filters.
         *
         *     Loads the discovered project from ``request.app.state.project_root`` and
         *     delegates filtering to :class:`TicketService`; ``total`` is the number of
         *     matching items (there is no pagination in the MVP).
         */
        readonly get: operations["list_tickets_api_v1_tickets_get"];
        readonly put?: never;
        /**
         * Create Ticket
         * @description Create the ticket described by ``payload``, or preview it when ``?dryRun=true``.
         *
         *     The status code follows the RESULT rather than the query flag: an apply reports
         *     ``201 Created``, a dry-run ``200 OK``, because a preview creates nothing and a
         *     ``201`` would tell the SPA (and any cache between them) that it did. Setting
         *     ``response.status_code`` overrides the route's declared default, which stays ``201``
         *     so that remains the documented success code.
         *
         *     Delegates to :meth:`~factory_console.services.write_service.WriteService.create`,
         *     whose ``WriteConflict`` (409) propagates for an id that already exists.
         */
        readonly post: operations["create_ticket_api_v1_tickets_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/tickets/{ticket_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Ticket
         * @description Return the full :class:`Ticket` for ``ticket_id`` with run-state resolved.
         *
         *     ``ticket_id`` is validated at the ``Path`` boundary against the shared
         *     :data:`TICKET_ID_PATTERN` (an invalid id becomes the ``invalid_ticket_id``
         *     400 envelope and never reaches the adapter). Loads the discovered project and
         *     delegates to :class:`TicketService`, whose ``TicketNotFound`` propagates to the
         *     domain-error handler as a 404 for an id absent from the manifest.
         */
        readonly get: operations["get_ticket_api_v1_tickets__ticket_id__get"];
        /**
         * Edit Ticket
         * @description Apply ``payload`` to ``ticket_id``, or preview the edit when ``?dryRun=true``.
         *
         *     Always ``200``: an edit creates no resource on either path. Delegates to
         *     :meth:`~factory_console.services.write_service.WriteService.edit`, whose
         *     ``TicketNotFound`` (404) and ``TicketNotMutable`` (409, the todo-only editing rule)
         *     propagate to the registered handlers.
         */
        readonly put: operations["edit_ticket_api_v1_tickets__ticket_id__put"];
        readonly post?: never;
        /**
         * Delete Ticket
         * @description Delete ``ticket_id``, or preview the delete when ``?dryRun=true``.
         *
         *     Always ``200`` with the uniform :class:`WriteResult` body rather than a bodiless
         *     ``204``, because the SPA renders the delete's diff in the same confirmation view as
         *     a create or an edit. Delegates to
         *     :meth:`~factory_console.services.write_service.WriteService.delete`, whose
         *     ``TicketNotFound`` (404) and ``TicketNotMutable`` (409) propagate to the registered
         *     handlers.
         */
        readonly delete: operations["delete_ticket_api_v1_tickets__ticket_id__delete"];
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/tickets/{ticket_id}/deps": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Ticket Deps
         * @description Return the :class:`DepNeighborhood` for ``ticket_id``.
         *
         *     ``ticket_id`` is validated at the ``Path`` boundary against the shared
         *     :data:`TICKET_ID_PATTERN` (an invalid id becomes the ``invalid_ticket_id``
         *     400 envelope and never reaches the adapter). Loads the discovered project and
         *     delegates to :class:`DepsService`, whose ``TicketNotFound`` propagates to the
         *     domain-error handler as a 404 for an id absent from the manifest.
         */
        readonly get: operations["get_ticket_deps_api_v1_tickets__ticket_id__deps_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/health": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Health
         * @description Return the liveness probe with the resolved ``projectRoot`` from ``app.state``.
         *
         *     Reads ``version`` and ``project_root`` that ``create_app`` stashed on
         *     ``app.state`` at boot and trusts them: ``create_app`` binds a non-optional
         *     ``project_root`` (the CLI always discovers a root; tests always pass a fixture
         *     root), so — like its sibling handlers and the ``version`` read beside it — this
         *     reads the root directly and lets Pydantic serialize the ``Path`` to a string.
         */
        readonly get: operations["get_health_api_v1_health_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/roadmap": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Roadmap
         * @description Return the project's full :class:`Roadmap`, or :class:`RoadmapAbsent`.
         *
         *     Loads the discovered project from ``request.app.state.project_root`` and calls
         *     ``adapter.get_roadmap(project)``, returning the full :class:`Roadmap` — its
         *     ``bodyMarkdown``, ``bodyHtml``, and structured ``milestones[]`` — when the
         *     project has one, else :class:`RoadmapAbsent`. Does no error handling of its
         *     own: a ``ProjectNotFound`` from ``load_project`` or a ``RoadmapUnreadable``
         *     (500) from ``adapter.get_roadmap`` propagates to the registered domain-error
         *     handler, which renders the mapped envelope.
         */
        readonly get: operations["get_roadmap_api_v1_roadmap_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/search": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Search
         * @description Return the ranked :class:`SearchHit` s matching the full-text query ``q``.
         *
         *     ``q`` is required; a blank or whitespace-only value yields an empty result
         *     (``{items: [], total: 0}``) rather than a validation error. ``limit`` bounds
         *     the number of hits to ``ge=1``/``le=200`` (default 50) — an out-of-range value
         *     is rejected at the ``Query`` boundary as the ``validation_error`` 422 envelope
         *     and never reaches the service. Loads the discovered project from
         *     ``request.app.state.project_root`` and delegates ranking to
         *     :class:`SearchService`; ``total`` is the number of returned items.
         */
        readonly get: operations["search_api_v1_search_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/graph": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Graph
         * @description Return the whole-project dependency :class:`TicketGraph`.
         *
         *     Reads the discovered root from ``request.app.state.project_root`` — a ``Path``
         *     ``create_app`` requires at boot — loads the target project, and returns the
         *     graph resolved by :class:`GraphService`. Returns the ``TicketGraph`` domain
         *     model directly so OpenAPI publishes its nodes+edges shape. Raises nothing
         *     itself: a ``ProjectNotFound`` from the adapter propagates to the registered
         *     domain-error handler, which maps it to the 404 envelope.
         */
        readonly get: operations["get_graph_api_v1_graph_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/events": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Events
         * @description Stream live :class:`ChangeEvent`s to the client as ``text/event-stream``.
         *
         *     Delegates the entire stream body to
         *     :func:`~factory_console.services.events_service.sse_event_stream`, which yields
         *     the initial ``ready`` frame, an ``event: change`` frame per file change while
         *     the injected ``watcher`` is present, and periodic ``: keepalive`` comments,
         *     releasing the watcher subscription when the client disconnects. The
         *     ``no-cache`` / ``X-Accel-Buffering: no`` headers keep the long-lived stream
         *     un-cached and un-buffered by any intermediary.
         */
        readonly get: operations["events_api_v1_events_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/spend": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Spend
         * @description Return the project's aggregated spend, or an explicit "no ledger" body.
         *
         *     Reads the discovered root from ``request.app.state.project_root`` — a ``Path``
         *     ``create_app`` requires at boot. With no ledger the response is
         *     ``source.found: false`` over zeroed totals; with one, it is the aggregate of
         *     every entry that parsed, plus the line numbers and reasons of those that did
         *     not. A ledger that exists but could not be read at all is the third case, and
         *     says so with ``source.read: false`` rather than passing its zeroed totals off
         *     as a measurement. The ledger's ``excerpt`` and ``session_id`` are projected
         *     nowhere.
         */
        readonly get: operations["get_spend_api_v1_spend_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/runs": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * List Runs
         * @description Return one :class:`RunRecord` per manifest ticket, in manifest order.
         *
         *     Loads the discovered project from ``request.app.state.project_root`` and delegates
         *     the whole composition to :class:`RunService` over the injected
         *     :class:`FileAdapter` and :class:`RunArtifactReader`. ``total`` is the number of
         *     records, which is the manifest's ticket count and not a count of tickets that have
         *     artifacts — there is no filtering and no pagination.
         */
        readonly get: operations["list_runs_api_v1_runs_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ArtifactRead
         * @description The result of reading ONE ``.factory`` JSON artifact: what it said, or why not.
         *
         *     Exactly one of the two outcomes holds: ``reason is None`` iff ``data`` is a
         *     successfully parsed JSON object. When ``reason`` is set, ``data`` is ``None``; a
         *     caller may therefore branch on either field and reach the same answer.
         *
         *     That ``iff`` is ENFORCED (:meth:`_exactly_one_outcome`), not merely documented.
         *     Both fields default to ``None``, so ``ArtifactRead(path=p)`` — an easy thing for a
         *     consumer or a test double to write for a case it forgot to name — would otherwise
         *     be accepted in precisely the state the paragraph above says cannot exist, and the
         *     two blessed branches would then DISAGREE about it: a caller testing ``reason is
         *     None`` reads it as a clean read and subscripts ``data`` into a ``TypeError``, while
         *     a caller testing ``data is None`` renders an empty state. That is the same
         *     absent/malformed collapse this type exists to prevent, so it is rejected at
         *     construction — the rule :class:`~factory_console.domain.run_state_source.JsonRunState`
         *     and :class:`~factory_console.domain.write.WriteResult` already set for their own
         *     two-field invariants.
         *
         *     ``path`` is carried on both outcomes — including ``absent`` — because "which
         *     file was this about" is exactly what an operator needs to act on a reason.
         *
         *     ``data`` is DELIBERATELY an untyped ``dict[str, Any]`` and not a modeled
         *     schema with named fields. This ticket (T88) is the reading layer only: it
         *     knows how to answer "does this artifact exist and is it a JSON object", and
         *     it has no captured real artifact to verify field names against — modeling
         *     fields from guesswork would ship a schema that silently rejects what the
         *     factory actually writes. Composing these into a per-ticket record is
         *     :class:`~factory_console.domain.run_record.RunRecord`'s job (T89), and it
         *     named the two SOURCES rather than their fields: it carries each
         *     :class:`ArtifactRead` verbatim, so ``data`` is still untyped there and this
         *     paragraph still governs it. Do not "improve" this into a typed schema — here
         *     or there — until a real captured artifact exists to verify against.
         */
        readonly ArtifactRead: {
            /**
             * Path
             * Format: path
             */
            readonly path: string;
            /** Data */
            readonly data?: {
                readonly [key: string]: unknown;
            } | null;
            /** Reason */
            readonly reason?: ("absent" | "unreadable" | "unparseable" | "too_large") | null;
        };
        /**
         * DepNeighborhood
         * @description A ticket with its direct dependency edges and any unresolved dep ids.
         *
         *     ``unresolvedDeps`` holds ids listed in the ticket's ``dependsOn`` that have
         *     no matching ticket in the manifest.
         */
        readonly DepNeighborhood: {
            readonly ticket: components["schemas"]["TicketSummary"];
            /** Directdeps */
            readonly directDeps?: readonly components["schemas"]["TicketSummary"][];
            /** Directdependents */
            readonly directDependents?: readonly components["schemas"]["TicketSummary"][];
            /** Unresolveddeps */
            readonly unresolvedDeps?: readonly string[];
        };
        /**
         * DiffPreview
         * @description The set of per-file diffs a write produces, keyed by ticket id.
         */
        readonly DiffPreview: {
            /** Ticketid */
            readonly ticketId: string;
            /** Files */
            readonly files?: readonly components["schemas"]["FileDiff"][];
        };
        /**
         * FileDiff
         * @description A single file's planned or applied change, as a unified diff.
         *
         *     ``path`` is project-relative POSIX; ``changeKind`` classifies the change;
         *     ``diff`` is the unified-diff text the SPA renders.
         */
        readonly FileDiff: {
            /** Path */
            readonly path: string;
            /**
             * Changekind
             * @enum {string}
             */
            readonly changeKind: "create" | "modify" | "delete";
            /** Diff */
            readonly diff: string;
        };
        /**
         * GraphEdge
         * @description A directed dependency edge: ``source`` depends on ``target``.
         *
         *     Only edges whose ``target`` resolves to a known node are emitted (dangling
         *     ``dependsOn`` ids are intentionally NOT edges, consistent with
         *     :attr:`~factory_console.domain.deps.DepNeighborhood.unresolvedDeps`); self-loops
         *     are dropped. Frozen and ``extra='forbid'`` like the other domain models.
         */
        readonly GraphEdge: {
            /** Source */
            readonly source: string;
            /** Target */
            readonly target: string;
        };
        /**
         * GraphNode
         * @description One ticket as a graph node, coloured by its resolved run-state.
         *
         *     Carries the same identity/classification fields as the list-view summary —
         *     ``id``, ``title``, ``status``, ``track``, ``milestone`` — plus the
         *     ``runState`` the shared projection already resolved, so a node's colour
         *     matches the list and deps views. Frozen and ``extra='forbid'`` like the other
         *     domain models.
         */
        readonly GraphNode: {
            /** Id */
            readonly id: string;
            /** Title */
            readonly title: string;
            /** Status */
            readonly status: string;
            /** Track */
            readonly track?: string | null;
            /** Milestone */
            readonly milestone?: string | null;
            readonly runState: components["schemas"]["RunState"];
        };
        /** HTTPValidationError */
        readonly HTTPValidationError: {
            /** Detail */
            readonly detail?: readonly components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Liveness probe body: service ``ok``, its ``version``, and the bound ``projectRoot``.
         */
        readonly HealthResponse: {
            /** Ok */
            readonly ok: boolean;
            /** Version */
            readonly version: string;
            /**
             * Projectroot
             * Format: path
             */
            readonly projectRoot: string;
        };
        /**
         * LevelSpend
         * @description One agent level's share of the bill — how much of it was review, not build.
         *
         *     ``level`` is the ledger's ``level`` field as written (``ticket``, and whatever
         *     else the factory names): the vocabulary belongs to the factory, so no closed
         *     set is enumerated here and an unrecognised level appears rather than vanishing.
         */
        readonly LevelSpend: {
            /** Level */
            readonly level: string;
            /**
             * Costusd
             * @default 0
             */
            readonly costUsd: number;
            /**
             * Entries
             * @default 0
             */
            readonly entries: number;
        };
        /**
         * ModelSpend
         * @description One model's project-wide share of the bill.
         *
         *     ``model`` is the factory's model id VERBATIM (e.g. ``claude-opus-4-8[1m]``).
         *     Nothing here maps it to a display name: mapping is the view's job, and a
         *     mapping applied at this layer would silently hide a model the console has not
         *     heard of behind whatever its fallback happened to be.
         *
         *     Distinct from the ledger's same-named
         *     :class:`~factory_console.domain.ledger.ModelSpend`, which is the RAW shape of
         *     one ``by_model`` value on one entry. This is the aggregate across every entry.
         *
         *     ``tokens.total`` is the SUM of one total per contributing entry, and each of
         *     those is arrived at differently: an entry with a ``by_model`` breakdown carries
         *     no total there, so its contribution is derived (the four counts summed), while
         *     an entry with no breakdown contributes the entry's own written ``total``. A
         *     model fed by both kinds therefore reports a total that need NOT equal this
         *     row's other four fields summed — the factory's written total is its own
         *     measurement, not a restatement of the parts, and this row keeps it rather than
         *     quietly replacing it with a figure the ledger never recorded.
         */
        readonly ModelSpend: {
            /** Model */
            readonly model: string;
            /**
             * Costusd
             * @default 0
             */
            readonly costUsd: number;
            /**
             * @default {
             *       "input": 0,
             *       "output": 0,
             *       "cacheRead": 0,
             *       "cacheCreation": 0,
             *       "total": 0
             *     }
             */
            readonly tokens: components["schemas"]["SpendTokens"];
        };
        /**
         * Project
         * @description Resolved paths for one App Factory project, discovered per request.
         *
         *     ``roadmapPath``, ``runStateDir`` and ``runStateSource`` are ``None`` when the
         *     corresponding file or directory is absent from the target project (all are
         *     optional in the project layout).
         *
         *     ``runStateSource`` is the resolved run-state artifact — the factory's
         *     ``.factory/run-state.json`` OR a legacy marker directory — and is what
         *     run-state reads dispatch on. ``runStateDir`` keeps its original meaning
         *     exactly: a path ONLY when the resolved source is a directory, so a
         *     JSON-sourced project has ``runStateDir is None``. Read run-state through
         *     ``runStateSource``; ``runStateDir`` answers only "which directory, if any, is
         *     off-limits to the writer".
         */
        readonly Project: {
            /**
             * Rootpath
             * Format: path
             */
            readonly rootPath: string;
            /**
             * Ticketsmanifestpath
             * Format: path
             */
            readonly ticketsManifestPath: string;
            /**
             * Ticketsdir
             * Format: path
             */
            readonly ticketsDir: string;
            /** Roadmappath */
            readonly roadmapPath?: string | null;
            /** Runstatedir */
            readonly runStateDir?: string | null;
            readonly runStateSource?: components["schemas"]["RunStateSource"] | null;
            /**
             * Discoveredat
             * Format: date-time
             */
            readonly discoveredAt: string;
        };
        /**
         * Roadmap
         * @description The project roadmap document (``ROADMAP.md``).
         *
         *     ``milestones`` is the structured breakdown parsed from the body — empty for a
         *     body with no ``## `` headings — leaving ``bodyMarkdown``/``bodyHtml`` as the
         *     full document for verbatim rendering.
         */
        readonly Roadmap: {
            /**
             * Path
             * Format: path
             */
            readonly path: string;
            /** Bodymarkdown */
            readonly bodyMarkdown: string;
            /** Bodyhtml */
            readonly bodyHtml: string;
            /** Milestones */
            readonly milestones?: readonly components["schemas"]["RoadmapMilestone"][];
        };
        /**
         * RoadmapAbsent
         * @description Response when the project has no roadmap: ``present: false``.
         *
         *     The backend-owned discriminator: :class:`~factory_console.domain.deps.Roadmap`
         *     carries no ``present`` field, so the frontend discriminates the present branch
         *     from this absent one on that key's presence.
         */
        readonly RoadmapAbsent: {
            /**
             * Present
             * @default false
             * @constant
             */
            readonly present: false;
        };
        /**
         * RoadmapItem
         * @description A single milestone list-item parsed from ``ROADMAP.md``.
         *
         *     ``text`` is the cleaned item label (marker and checkbox stripped); ``done``
         *     reflects the checkbox state (``True``/``False`` for ``[x]``/``[ ]``, ``None``
         *     when the item carries no checkbox); ``ticketId`` is the item's linked ticket
         *     id when one is present, else ``None``.
         */
        readonly RoadmapItem: {
            /** Text */
            readonly text: string;
            /** Ticketid */
            readonly ticketId?: string | null;
            /** Done */
            readonly done?: boolean | null;
        };
        /**
         * RoadmapMilestone
         * @description A ``## `` heading from ``ROADMAP.md`` with its list of items.
         */
        readonly RoadmapMilestone: {
            /** Name */
            readonly name: string;
            /** Items */
            readonly items?: readonly components["schemas"]["RoadmapItem"][];
        };
        /**
         * RunListResponse
         * @description Envelope for the runs list: one record per manifest ticket, and their count.
         */
        readonly RunListResponse: {
            /** Items */
            readonly items: readonly components["schemas"]["RunRecord"][];
            /** Total */
            readonly total: number;
        };
        /**
         * RunRecord
         * @description The factory's two per-ticket artifacts for ONE manifest ticket, reasons and all.
         *
         *     Both artifacts are carried as the reader's own :class:`ArtifactRead`
         *     VERBATIM, and that is the whole point of this type. Each ``ArtifactRead``
         *     already pairs "here is the object" with, on the other branch, exactly WHY
         *     there is none — ``absent`` (the factory never wrote it), ``unreadable``
         *     (nothing was read: the bytes would not come, or the path could not be proven
         *     safe to read at all, so existence is NOT established — see
         *     :data:`~factory_console.domain.runs.ArtifactSkipReason`, which forbids
         *     inferring it), ``unparseable``
         *     (it answered, unintelligibly) or ``too_large``. Collapsing the pair into a
         *     summary — a ``hasResult`` boolean, a count of missing sources, a bare
         *     ``None`` — would put back precisely the ambiguity T88 built the type to
         *     remove: a blank field that means either "nothing was recorded" or "we did not
         *     look". Every absent source must be NAMED, per source. Do not flatten these.
         *
         *     The two sources are independent: a lane can have written a result and no
         *     receipt, or a corrupt receipt beside a clean result, so each field carries its
         *     own reason and neither may be inferred from the other.
         *
         *     ``ticketId`` comes from the manifest, not from the artifacts — the artifacts
         *     are keyed BY it — and is :data:`~factory_console.domain.ticket.TicketId`
         *     constrained like every other id on the domain surface.
         */
        readonly RunRecord: {
            /** Ticketid */
            readonly ticketId: string;
            readonly result: components["schemas"]["ArtifactRead"];
            readonly receipt: components["schemas"]["ArtifactRead"];
        };
        /**
         * RunState
         * @description A ticket's run-state, derived from the project's resolved run-state source.
         *
         *     Subclasses ``str`` so a member compares and serializes as its string value
         *     (``RunState.todo == "todo"``); the value is the name its source uses.
         * @enum {string}
         */
        readonly RunState: "todo" | "in-flight" | "ready" | "merged" | "in_progress" | "in_part" | "in_submilestone" | "flagged" | "failed" | "needs_human" | "unknown" | "absent" | "unreadable";
        /**
         * RunStateSource
         * @description A resolved run-state artifact: its form (``kind``) and where it lives.
         *
         *     Frozen and ``extra="forbid"`` like every other domain model, and carried on
         *     :class:`~factory_console.domain.project.Project` so the whole request reads
         *     through ONE resolution rather than each call site re-probing the filesystem.
         */
        readonly RunStateSource: {
            /**
             * Kind
             * @enum {string}
             */
            readonly kind: "json" | "directory";
            /**
             * Path
             * Format: path
             */
            readonly path: string;
        };
        /**
         * SearchHit
         * @description One ranked full-text search result: a ticket summary, its score, and hits.
         *
         *     ``score`` is the summed per-field weight the ranking accrued for this ticket
         *     (higher is more relevant); ``matchedFields`` names the fields any query token
         *     hit, in a stable field order (``id``, ``title``, ``provides``,
         *     ``bodyMarkdown``). Frozen and ``extra='forbid'`` like the other domain models.
         *
         *     The ``ScoredTicket`` → ``SearchHit`` re-key both adapters share lives in
         *     ``file_adapter/search.py``'s ``to_search_hits`` — next to its ``ScoredTicket``
         *     input, importing this model downward (the allowed ``file_adapter → domain``
         *     direction) — so ``domain`` never has to depend on a ``file_adapter`` type.
         */
        readonly SearchHit: {
            readonly ticket: components["schemas"]["TicketSummary"];
            /** Score */
            readonly score: number;
            /** Matchedfields */
            readonly matchedFields?: readonly string[];
        };
        /**
         * SearchResponse
         * @description Envelope for the search results: the ranked hits and their count.
         */
        readonly SearchResponse: {
            /** Items */
            readonly items: readonly components["schemas"]["SearchHit"][];
            /** Total */
            readonly total: number;
        };
        /**
         * SkippedLineInfo
         * @description A ledger line that did not parse, over HTTP: which line, and why.
         *
         *     T79's :class:`~factory_console.domain.ledger.SkippedLine` also carries an
         *     ``excerpt`` of the offending line; it is NOT projected here. The excerpt exists
         *     for a human reading the file, and the ledger is a file the console only
         *     observes — putting a slice of its raw bytes on the wire would widen what this
         *     read-only endpoint can disclose for no view that needs it.
         *
         *     ``lineNo`` is ``0`` when the failure belongs to the whole file rather than to
         *     any one line (unreadable, or over the reader's size cap).
         */
        readonly SkippedLineInfo: {
            /** Lineno */
            readonly lineNo: number;
            /**
             * Reason
             * @enum {string}
             */
            readonly reason: "not_json" | "invalid_entry" | "partial_line" | "file_too_large" | "unreadable";
        };
        /**
         * SourceInfo
         * @description Whether this project HAS a ledger, whether it could be READ, and where it is.
         *
         *     THE field that keeps "no ledger" from being read as "$0.00". ``found: false``
         *     is the fresh-clone case and a client must be able to act on it directly, rather
         *     than inferring absence from a zero total — which an empty ledger also produces,
         *     and which for an unmeasured project would be a false statement about real money.
         *
         *     ``read`` carries the SAME distinction one step further, because ``found`` alone
         *     does not survive a ledger that exists and could not be opened. A file over the
         *     reader's size cap, or one that cannot be stat'd or read at all, yields zero
         *     entries — so ``found: true`` over zeroed totals would state that a ledger WAS
         *     read and measured nothing, which for an 11 MiB file full of real lanes is the
         *     same false statement ``found`` exists to prevent, merely relocated. ``read:
         *     false`` says the bill is UNKNOWN rather than zero; the reason is in
         *     :attr:`SpendResponse.skipped`, at ``lineNo`` 0.
         *
         *     So ``read`` means "the figures below came from actually reading a file", and it
         *     defaults to ``False`` — the honest value for the no-ledger case, where there was
         *     nothing to read. ``totals`` is a MEASURED zero only when ``read`` is true; on
         *     ``found: true, read: false`` it is a placeholder for a bill nobody could count.
         *
         *     ``path`` is where the console LOOKED, not proof that anything was there — it
         *     is populated on all three outcomes, including ``found: false``. A view whose
         *     entire job in the no-ledger case is to explain the absence has to be able to
         *     name the place, and reading that off ``found`` instead would make the
         *     frontend restate the ledger's location in its own source. ``found`` and
         *     ``read``, not this field, are what say whether the file exists and was
         *     parsed. It is ``None`` only when the path could not be formed at all.
         */
        readonly SourceInfo: {
            /** Found */
            readonly found: boolean;
            /**
             * Read
             * @default false
             */
            readonly read: boolean;
            /** Path */
            readonly path?: string | null;
        };
        /**
         * SpendResponse
         * @description The ``GET /api/v1/spend`` body: a :class:`SpendReport` plus how it was read.
         *
         *     Extends the pure report with the two facts only the caller holds — whether the
         *     ledger existed at all (:class:`SourceInfo`) and which of its lines could not be
         *     read — by SUBCLASSING it, so the wire shape cannot drift from the aggregate as
         *     fields are added to one and not the other.
         *
         *     ``skippedOmitted`` counts lines that failed beyond the reader's detail cap. It
         *     is not decoration: T79 caps how many skipped lines it materialises but keeps
         *     counting them, and dropping that count here would make a catastrophically
         *     corrupt ledger report exactly as partial as a mildly corrupt one.
         *
         *     ``len(skipped) + skippedOmitted`` is the exact number of lines missing from
         *     :attr:`SpendReport.totals` — **for per-line failures only**. A skip at
         *     ``lineNo`` 0 is not a line: it reports that the WHOLE file was not read
         *     (``unreadable``, or over the reader's size cap), so it stands for an unknown
         *     number of lines, not for one. That case is exactly ``source.read: false``, and a
         *     client counting unparsed lines must branch on it rather than render "1 line
         *     could not be read" over a ledger nothing ever opened.
         */
        readonly SpendResponse: {
            /**
             * Attribution
             * @default full-to-each-id
             * @constant
             */
            readonly attribution: "full-to-each-id";
            /**
             * @default {
             *       "costUsd": 0,
             *       "entries": 0,
             *       "tokens": {
             *         "cacheCreation": 0,
             *         "cacheRead": 0,
             *         "input": 0,
             *         "output": 0,
             *         "total": 0
             *       }
             *     }
             */
            readonly totals: components["schemas"]["SpendTotals"];
            /** Byticket */
            readonly byTicket?: readonly components["schemas"]["TicketSpend"][];
            /** Bymodel */
            readonly byModel?: readonly components["schemas"]["ModelSpend"][];
            /** Bylevel */
            readonly byLevel?: readonly components["schemas"]["LevelSpend"][];
            readonly source: components["schemas"]["SourceInfo"];
            /** Skipped */
            readonly skipped?: readonly components["schemas"]["SkippedLineInfo"][];
            /**
             * Skippedomitted
             * @default 0
             */
            readonly skippedOmitted: number;
        };
        /**
         * SpendTokens
         * @description Summed token counts in the console's OWN camelCase wire vocabulary.
         *
         *     A near-twin of :class:`~factory_console.domain.ledger.TokenCounts`, and
         *     deliberately NOT that class. The ledger's model is shaped by the FILE: it
         *     spells the factory's ``cache_read``/``cache_creation`` and it is
         *     ``extra="ignore"`` because another program owns that format. Both traits are
         *     wrong for a response — the REST v1 contract is camelCase, and a shape this repo
         *     builds AND serialises end to end takes the house ``extra="forbid"``.
         *
         *     Reusing the ledger model here would publish snake_case keys in the one nested
         *     object of an otherwise camelCase body, and would leave the console's published
         *     contract to be rewritten by a future edit to a model that exists to track
         *     someone else's file. So the parse shape and the wire shape are separate types,
         *     converted in exactly one place —
         *     :meth:`~factory_console.domain.spend_calc._Tokens.frozen`.
         */
        readonly SpendTokens: {
            /**
             * Input
             * @default 0
             */
            readonly input: number;
            /**
             * Output
             * @default 0
             */
            readonly output: number;
            /**
             * Cacheread
             * @default 0
             */
            readonly cacheRead: number;
            /**
             * Cachecreation
             * @default 0
             */
            readonly cacheCreation: number;
            /**
             * Total
             * @default 0
             */
            readonly total: number;
        };
        /**
         * SpendTotals
         * @description What the whole read cost: dollars, entry count, and summed token counts.
         *
         *     ``entries`` counts the ledger entries that PARSED. It is deliberately reported
         *     beside the money so a caller can compare it against
         *     :attr:`SpendResponse.skipped` and see that a total was computed over 40 of 43
         *     lines — a partial bill that says so, rather than a confident wrong number.
         *
         *     ``tokens`` sums the entries' own ``tokens`` objects field by field, including
         *     the factory's written ``total``; it is not recomputed from the parts, so it
         *     reports what the factory measured.
         */
        readonly SpendTotals: {
            /**
             * Costusd
             * @default 0
             */
            readonly costUsd: number;
            /**
             * Entries
             * @default 0
             */
            readonly entries: number;
            /**
             * @default {
             *       "input": 0,
             *       "output": 0,
             *       "cacheRead": 0,
             *       "cacheCreation": 0,
             *       "total": 0
             *     }
             */
            readonly tokens: components["schemas"]["SpendTokens"];
        };
        /**
         * Ticket
         * @description A manifest entry joined with its rendered ``.md`` body.
         *
         *     ``raw`` preserves the unmodified manifest entry — including fields this model
         *     does not name — for forward-compatibility with future factory versions.
         *     ``extra='forbid'`` governs the model's *own* fields; it does not restrict the
         *     contents of the ``raw`` mapping. ``runState`` defaults to
         *     :attr:`RunState.unknown` and is resolved per request by the service on the
         *     detail path (the manifest/enrichment build sites leave it at the default).
         */
        readonly Ticket: {
            /** Id */
            readonly id: string;
            /** Title */
            readonly title: string;
            /** Status */
            readonly status: string;
            /** Track */
            readonly track?: string | null;
            /** Milestone */
            readonly milestone?: string | null;
            /** @default unknown */
            readonly runState: components["schemas"]["RunState"];
            /** Dependson */
            readonly dependsOn?: readonly string[];
            /** Provides */
            readonly provides?: readonly string[];
            /** Files */
            readonly files?: readonly string[];
            /**
             * Filepath
             * Format: path
             */
            readonly filePath: string;
            /** Bodymarkdown */
            readonly bodyMarkdown: string;
            /** Bodyhtml */
            readonly bodyHtml: string;
            /** Raw */
            readonly raw: {
                readonly [key: string]: unknown;
            };
        };
        /**
         * TicketDraft
         * @description Inbound request body to CREATE a ticket.
         *
         *     ``id`` is validated against :data:`TICKET_ID_PATTERN` at this boundary; the
         *     rest mirror the manifest/body fields a new ticket carries. ``frontMatter``
         *     holds arbitrary extra YAML front-matter keys not named explicitly.
         */
        readonly TicketDraft: {
            /** Id */
            readonly id: string;
            /** Title */
            readonly title: string;
            /** Track */
            readonly track?: string | null;
            /** Milestone */
            readonly milestone?: string | null;
            /** Dependson */
            readonly dependsOn?: readonly string[];
            /**
             * Provides
             * @default
             */
            readonly provides: string;
            /** Files */
            readonly files?: readonly string[];
            /** Bodymarkdown */
            readonly bodyMarkdown: string;
            /** Frontmatter */
            readonly frontMatter?: {
                readonly [key: string]: unknown;
            };
        };
        /**
         * TicketEdit
         * @description Inbound request body to EDIT a ticket.
         *
         *     Identical to :class:`TicketDraft` minus ``id`` — the id of the ticket being
         *     edited comes from the path parameter, not the body.
         */
        readonly TicketEdit: {
            /** Title */
            readonly title: string;
            /** Track */
            readonly track?: string | null;
            /** Milestone */
            readonly milestone?: string | null;
            /** Dependson */
            readonly dependsOn?: readonly string[];
            /**
             * Provides
             * @default
             */
            readonly provides: string;
            /** Files */
            readonly files?: readonly string[];
            /** Bodymarkdown */
            readonly bodyMarkdown: string;
            /** Frontmatter */
            readonly frontMatter?: {
                readonly [key: string]: unknown;
            };
        };
        /**
         * TicketGraph
         * @description The whole-project dependency DAG: run-state-coloured nodes and edges.
         *
         *     ``nodes`` are the ticket summaries in list order; ``edges`` are the resolved,
         *     self-loop-free, de-duplicated ``dependsOn`` relations. The frontend maps this
         *     payload to Cytoscape element format (not this model's concern). Frozen and
         *     ``extra='forbid'`` like the other domain models.
         */
        readonly TicketGraph: {
            /** Nodes */
            readonly nodes?: readonly components["schemas"]["GraphNode"][];
            /** Edges */
            readonly edges?: readonly components["schemas"]["GraphEdge"][];
        };
        /**
         * TicketListResponse
         * @description Envelope for the tickets list: the matching summaries and their count.
         */
        readonly TicketListResponse: {
            /** Items */
            readonly items: readonly components["schemas"]["TicketSummary"][];
            /** Total */
            readonly total: number;
        };
        /**
         * TicketSpend
         * @description One ticket id's attributed spend, under :data:`ATTRIBUTION_RULE`.
         *
         *     ``attributedCostUsd`` is named for the rule: it is the sum of the FULL cost of
         *     every entry naming this ticket, so summing this field across tickets does not
         *     give :attr:`SpendTotals.costUsd` and is not meant to.
         *
         *     ``models`` lists the model ids seen on this ticket's entries, sorted, as the
         *     factory wrote them — a set for the view to render, not a per-model breakdown
         *     (that is :class:`ModelSpend`, which is project-wide).
         */
        readonly TicketSpend: {
            /** Ticketid */
            readonly ticketId: string;
            /**
             * Attributedcostusd
             * @default 0
             */
            readonly attributedCostUsd: number;
            /**
             * Entries
             * @default 0
             */
            readonly entries: number;
            /** Models */
            readonly models?: readonly string[];
        };
        /**
         * TicketSummary
         * @description List-projection of a ticket for the tickets index view.
         *
         *     ``runState`` is resolved per request by probing the factory run-state
         *     directory; ``depCount`` / ``dependentCount`` come from reverse-indexing
         *     ``dependsOn`` across the manifest.
         */
        readonly TicketSummary: {
            /** Id */
            readonly id: string;
            /** Title */
            readonly title: string;
            /** Status */
            readonly status: string;
            /** Track */
            readonly track?: string | null;
            /** Milestone */
            readonly milestone?: string | null;
            readonly runState: components["schemas"]["RunState"];
            /** Depcount */
            readonly depCount: number;
            /** Dependentcount */
            readonly dependentCount: number;
        };
        /** ValidationError */
        readonly ValidationError: {
            /** Location */
            readonly loc: readonly (string | number)[];
            /** Message */
            readonly msg: string;
            /** Error Type */
            readonly type: string;
            /** Input */
            readonly input?: unknown;
            /** Context */
            readonly ctx?: Record<string, never>;
        };
        /**
         * WriteResult
         * @description Uniform envelope returned by every write endpoint (apply or dry-run).
         *
         *     Two shapes:
         *
         *     * **Apply** → ``applied=True``, ``ticket`` set to the re-read
         *       :class:`~factory_console.domain.ticket.Ticket`, ``changedFiles`` the paths
         *       actually written, ``diff`` the preview of what was written.
         *     * **Dry-run** → ``applied=False``, ``ticket=None``, ``changedFiles`` the
         *       planned paths, ``diff`` the preview of what would be written.
         */
        readonly WriteResult: {
            /** Applied */
            readonly applied: boolean;
            /** Ticketid */
            readonly ticketId: string;
            /** Changedfiles */
            readonly changedFiles?: readonly string[];
            readonly diff: components["schemas"]["DiffPreview"];
            readonly ticket?: components["schemas"]["Ticket"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly get_project_api_v1_project_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    readonly list_tickets_api_v1_tickets_get: {
        readonly parameters: {
            readonly query?: {
                readonly status?: string | null;
                readonly track?: string | null;
                readonly milestone?: string | null;
                readonly q?: string | null;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["TicketListResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly create_ticket_api_v1_tickets_post: {
        readonly parameters: {
            readonly query?: {
                readonly dryRun?: boolean;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["TicketDraft"];
            };
        };
        readonly responses: {
            /** @description Dry-run preview: the diff that WOULD be written; nothing was created. */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["WriteResult"];
                };
            };
            /** @description Successful Response */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["WriteResult"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_ticket_api_v1_tickets__ticket_id__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly ticket_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Ticket"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly edit_ticket_api_v1_tickets__ticket_id__put: {
        readonly parameters: {
            readonly query?: {
                readonly dryRun?: boolean;
            };
            readonly header?: never;
            readonly path: {
                readonly ticket_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["TicketEdit"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["WriteResult"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly delete_ticket_api_v1_tickets__ticket_id__delete: {
        readonly parameters: {
            readonly query?: {
                readonly dryRun?: boolean;
            };
            readonly header?: never;
            readonly path: {
                readonly ticket_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["WriteResult"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_ticket_deps_api_v1_tickets__ticket_id__deps_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly ticket_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["DepNeighborhood"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_health_api_v1_health_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readonly get_roadmap_api_v1_roadmap_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Roadmap"] | components["schemas"]["RoadmapAbsent"];
                };
            };
        };
    };
    readonly search_api_v1_search_get: {
        readonly parameters: {
            readonly query: {
                readonly q: string;
                readonly limit?: number;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_graph_api_v1_graph_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["TicketGraph"];
                };
            };
        };
    };
    readonly events_api_v1_events_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": unknown;
                };
            };
        };
    };
    readonly get_spend_api_v1_spend_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SpendResponse"];
                };
            };
        };
    };
    readonly list_runs_api_v1_runs_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["RunListResponse"];
                };
            };
        };
    };
}
