// Post-codegen step for `pnpm codegen`: prepend a DO-NOT-EDIT banner to the
// openapi-typescript output so the generated file is clearly machine-owned.
// Runs after `openapi-typescript ... -o src/lib/api/types.ts --immutable`.
// Idempotent: re-running without a fresh codegen leaves the file untouched.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const TYPES_PATH = join(SCRIPT_DIR, '..', 'src', 'lib', 'api', 'types.ts');

const MARKER = 'DO NOT EDIT — regenerate with pnpm codegen';
const BANNER = [
	'/**',
	` * ${MARKER}`,
	' *',
	" * Generated by openapi-typescript from the server's /api/v1/openapi.json.",
	' * Any manual edit is overwritten the next time `pnpm codegen` runs.',
	' */',
	''
].join('\n');

function main() {
	let source;
	try {
		source = readFileSync(TYPES_PATH, 'utf8');
	} catch {
		console.error(
			`postcodegen: ${TYPES_PATH} not found — run \`pnpm codegen\` (openapi-typescript) first.`
		);
		process.exit(1);
		return;
	}

	// Idempotency: if the banner marker is already at the top, do nothing so a
	// standalone re-run does not double-prepend it.
	if (source.slice(0, BANNER.length + 64).includes(MARKER)) {
		return;
	}

	writeFileSync(TYPES_PATH, `${BANNER}\n${source}`, 'utf8');
	console.log('postcodegen: prepended DO-NOT-EDIT banner to src/lib/api/types.ts');
}

main();
